// 前端可用的 proxy 环境映射
export const proxyEnvMap = {
  mock: 'http://localhost:8000',
  ci: 'http://10.22.28.131:9100',
  dit: 'http://dit.fwdowb.net:9100',
  presit: 'http://10.22.168.115/',
  uat: 'https://uat-claims.fwd.com.hk',
  dev: 'https://dev-claims.fwd.com.hk',
  poc: 'http://10.22.171.87',
  sit: 'http://10.22.171.51',
  'support-test': 'https://support-opus-gtf.internal.fwd.com',
  'VN-LOCAL-UAT': 'http://10.22.171.109',
  'ID-LOCAL-UAT': 'http://10.22.171.127',
  'MY-LOCAL-UAT': 'http://10.22.171.134',
  'PH-LOCAL-UAT': 'http://10.22.171.113',
  'KH-LOCAL-UAT': 'http://10.22.171.117',
  'OPUS-LOCAL-UAT': 'http://10.22.171.80',
  'HK-LOCAL-UAT': 'http://10.22.171.53',
  'HK-LOCAL-STAGE': 'http://10.22.171.52',
  'ID-BU-SIT': 'https://sit-owb.fwd.co.id',
  'ID-BU-UAT': 'https://owb-uat.apse1.idn.np-api.fwd.com',
  'ID-PROD': 'https://owb.apse1.idn.api.fwd.com',
  'KH-PROD': 'http://operations-workbench.prd.kh.intranet',
  'KH-BU-UAT': 'http://operations-workbench.uat.kh.intranet',
  'KH-BU-SIT': 'http://operations-workbench.dev.kh.intranet',
  'MY-BU-UAT': 'https://operations-workbench.uat.my.intranet',
  'MY-STAGE': 'https://operations-workbench.ppd.my.intranet',
  'MY-FIB-UAT': 'http://opus-uat.my.intranet',
  'MY-BU-SIT': 'http://operations-workbench.sit.my.intranet',
  'MY-PROD': 'http://operations-workbench.my.intranet',
  'PH-PROD': 'https://owb.fwd.com.ph',
  'PH-BU-UAT': 'https://owb-uat.apse1.phl.np-api.fwd.com',
  'PH-BU-SIT': 'http://owb-sit.apse1.phl.np-api.fwd.com',
  'OPUS-HK-DEV': 'http://internal-alb-gtf-hkom-apse1-opus-dev-eks-269668519.ap-southeast-1.elb.amazonaws.com',
  'HK-PROD(DCP)': 'https://operations-workbench.fwd.com',
  'HK-BU-DEV(DCP)': 'https://dev-claims.fwd.com.hk',
  'HK-BU-UAT(DCP)': 'https://uat-claims.fwd.com.hk',
  'VN-BU-UAT': 'https://uat-owb.fwd.com.vn',
  'VN-BU-SIT': 'https://10.154.130.10',
  'VN-PRE-PROD': 'https://preprod-owb.fwd.com.vn',
  'VN-PROD': 'https://10.154.3.16',
  'MMT-opus-sit': 'https://opus-sit.fwd.com',
  'MMT-opus-uat': 'https://opus-uat.fwd.com',
  'MMT-opus-stage': 'https://opus-staging.fwd.com',
  'MMT-opus-prod': 'https://opus.fwd.com',
};

export type ProxyEnvKey = keyof typeof proxyEnvMap;
