import { BankAccount } from './BankAccount';
import { Contact } from './Contact';

export const Payee = {
  account: '',
  address: '',
  addressSearchResult: '',
  bankAccountName: '',
  bankAccountNo: '',
  bankCode: '',
  bpoBankAccountName: '',
  bpoBranchName: '',
  branchCode: '',
  branchName: '',
  claimNo: '',
  creator: '',
  dateOfBirth: null,
  email: '',
  firstName: '',
  gender: '',
  id: '',
  identityNo: '',
  identityType: '',
  middleName: '',
  modifier: '',
  organization: 0,
  passbookCode: '',
  passbookNo: '',
  payee: '',
  payeeBankAccountList: [BankAccount],
  payeeContactList: [Contact],
  payeeNo: '',
  payeeType: '',
  paymentAmount: 0,
  paymentMethod: '',
  paymentModel: '',
  phoneNo: '',
  postCode: '',
  relationshipWithInsured: '',
  scheduledDate: null,
  surname: '',
  transId: '',
  transferAccount: '',
  typeOfPayment: '',
  ctaCheckNo: '',
  ctaCheckDate: null,
  payoutAmount: 0,
  payoutCurrency: '',
  chequeRemark: '',
};
