enum ButtonCode {
  Submit = 'submit',
  Save = 'save',
  UnPend = 'unPend',
  Pend = 'pend',
  Split = 'split',
  Favorite = 'favorite',
  Withdrawal = 'withdrawal',
  Reject = 'reject',
  Image = 'image',
  Back = 'back',
  ReturnAppDoc = 'returnAppDoc',
  GenAppForm = 'genAppForm',
  Resume = 'resume',
  TblSearch = 'tblSearch',
  Urgent = 'urgent',
  BusinessCheck = 'businessCheck',
  SlaTime = 'slaTime',
  NonApplicableSubmit = 'nonApplicableSubmit',
  AppealCase = 'appeal-case',
  Upload = 'upload',
  Template = 'template',
  // revert现在当reject用/所以新加个reverts区分
  Revert = 'revert',
  Reverse = 'reverse',
  EndCase = 'endCase',
  Retry = 'retry',
  ESubmission = 'eSubmission',
  Appeal = 'appeal',
}

export default ButtonCode;
