import CaseCategory from 'enum/CaseCategory';
import { CustomerType } from 'claim/enum/customerType';

export const mapToCustomer = {
  [CaseCategory.TH_GC_CTG02]: CustomerType.CUS001,
  [CaseCategory.TH_GC_CTG03]: CustomerType.CUS001,
  [CaseCategory.TH_GC_CTG04]: CustomerType.CUS001,
  [CaseCategory.TH_GC_CTG06]: CustomerType.CUS001,
  [CaseCategory.TH_GC_CTG07]: CustomerType.CUS001,
  [CaseCategory.JP_PC_CTG01]: CustomerType.CUS001,
  [CaseCategory.JP_MC_CTG01]: CustomerType.CUS001,
  [CaseCategory.TH_GC_CTG05]: CustomerType.CUS001,
  [CaseCategory.TH_UD_CTG01]: CustomerType.CUS001,
  [CaseCategory.JP_CP_CTG001]: CustomerType.CUS001,
  [CaseCategory.PH_CLMUW_CTG001]: CustomerType.CUS001,
  [CaseCategory.JP_CLM_CTG01]: CustomerType.CUS001,
  [CaseCategory.PH_POS_CTG006]: CustomerType.CUS002,
  [CaseCategory.PH_POS_CTG005]: CustomerType.CUS002,
  [CaseCategory.JP_DD_CTG01]: CustomerType.CUS001,
  [CaseCategory.PH_POS_CTG004]: CustomerType.CUS002,
  [CaseCategory.BP_UP_CTG001]: CustomerType.CUS001,
  [CaseCategory.PH_POS_CTG003]: CustomerType.CUS002,
  [CaseCategory.PH_POS_CTG002]: CustomerType.CUS002,
  [CaseCategory.PH_POS_CTG001]: CustomerType.CUS002,
  [CaseCategory.PH_AP_CTG01]: CustomerType.CUS001,
  [CaseCategory.BP_AP_CTG01]: CustomerType.CUS001,
  [CaseCategory.DummyCase02]: CustomerType.CUS001,
  [CaseCategory.HK_CLM_CTG002]: CustomerType.CUS001,
  [CaseCategory.JP_CLM_CTG001]: CustomerType.CUS001,
  [CaseCategory.JP_CLM_CTG002]: CustomerType.CUS001,
  [CaseCategory.IDAC]: CustomerType.CUS001,
  [CaseCategory.HK_CLM_CTG001]: CustomerType.CUS001,
  [CaseCategory.BP_RUL_CTG002]: CustomerType.CUS001,
  [CaseCategory.Rule_Setup]: CustomerType.CUS001,
  [CaseCategory.BP_RUL_CTG001]: CustomerType.CUS001,
  [CaseCategory.IAPC]: CustomerType.CUS001,
  [CaseCategory.PH_CLM_CTG001]: CustomerType.CUS001,
  [CaseCategory.TH_IHB_CTG01]: CustomerType.CUS001,
  [CaseCategory.CC_DI01]: CustomerType.CUS001,
  [CaseCategory.RUW]: CustomerType.CUS001,
  [CaseCategory.BP_UD_CTG01]: CustomerType.CUS001,
  [CaseCategory.TH_DOC_CTG01]: CustomerType.CUS001,
  [CaseCategory.JP_PA_CTG01]: CustomerType.CUS001,
  [CaseCategory.TH_MC_CTG01]: CustomerType.CUS001,
  [CaseCategory.DummyCase]: CustomerType.CUS001,
  [CaseCategory.TH_GC_CTG01]: CustomerType.CUS001,
  [CaseCategory.Claim_Request]: CustomerType.CUS001,
  [CaseCategory.BP_IE_CTG001]: CustomerType.CUS001,
  [CaseCategory.HK_DC_CTG001]: CustomerType.CUS001,
};
