const previewData = {
  previewModeShow: false,
  previewResolve: null,
  previewModeData: {},
  previewSelectLetter: 0,
  previewEnclosure: {},
  previewSelectEnclosureIndex: null,
  isChange: false,
  title: null,
  previewModePageAtomConfig: [],
  previewForm: {},
};
export { previewData };

export default {
  caseNo: '',
  businessNo: '',
  inquiryBusinessNo: '',
  taskStatus: '',
  reasonConfigs: [],
  activityKey: '',
  caseCategory: '',
  taskId: '',
  currentReasonGroups: [],
  activedGroupKey: null,
  currentReasonGroupsBackup: [],
  historyGroupKey: null,
  historyReasonGroups: [],
  destRoleInfo: {},
  thPendPolicyReasonInfo: {},
  policyNoInfo: {},
  paymentNoArr: [],
  isPending: false,
  allDocumentTypes: [],
  attachDocArr: [],
  form: {},
  errorInfo: {},
  caseCategoryReasonConfigs: [],
  listMemos: {},
  listMemoSubType: {},
  reasonHaveMemoSubType: {},
  historyChangeTime: null,
  sendDataIdArr: [],
  viewReasonInfo: [],
  reminderIndex: '0',
  batchEnvoySelected: [],
  requestClientInfoList: [],
  retryListGroups: {},
  getProcessJobInfoTimeStamp: '',
  memoSubTypeList: {},
  sendCondition: {
    sendConditionShow: false,
    resultInfoStatus: '',
  },
  medicalProviderDicts: {},
  envoyEdit: true,
  envoyEditConfigs: [],
  ...previewData,
};
