import { paymentState } from 'process/Payment/_models';

export default {
  claimProcessData: {
    exchangeRateList: [],
  },
  claimEntities: {},
  treatmentPayableAddItem: null,
  currencyModalShowStatus: false,
  invoiceCurrencyObj: {
    invoiceId: '',
    invoiceCurrency: '',
    exchangeDate: '',
  },
  exchangeDateModalShowStatus: false,
  exchangeRateListForInvoice: [],
  policyOwnerList: [],
  searchInsuredObj: {
    policySource: 'Individual',
    firstName: '',
    middleName: '',
    surname: '',
    dateOfBirth: '',
    gender: '',
    clientId: '',
    policyId: '',
  },
  saveAgentNoList: [],
  isClickClaimRegister: false,
  procedurePayableItemAdd: {},
  otherProcedurePayableItemAdd: {},
  decisionMapping: [],
  taskDetail: {},
  serialClaimMap: [],
  serialClaimFlag: false,
  DrugsDetail: {
    allList: [],
    filterList: [],
    show: false,
    drugsListStore: [],
    total: 0,
    filterParams: {},
    searchState: false,
    page: 1,
    idx: 0,
  },
  claimPayableGroupList: [],
  popUpPayable: {},
  nameScreeningVisible: false,
  caseDetail: {},
  popupData: {},
  dictsOfDiagnosis: [],
  ...paymentState,
  dropdownMap: {
    treatmentProviderMap: {},
  },
  procedureModal: {
    show: false,
    searchContent: '',
    searchList: [],
    treatmentId: '',
    procedureId: '',
    current: 1,
    total: 0,
  },
  otherProcedureModal: {
    show: false,
    searchContent: '',
    searchList: [],
    treatmentId: '',
    otherProcedureId: '',
    current: 1,
    total: 0,
  },
};
