export default {
  insuredId: '',
  caseCategory: '',
  customerType: '',
  clientInfo: {},
  policyInfoList: [],
  claimHistoryList: [],
  c360SideBarPosHistoryList: [],
  diseaseNameList: [],
  existDocList: [],
  activeClientId: '',
  clientIdList: [],
  insuredPolicyIdList: [],
  sideBarOverallList: [],
  activeRole: '',
  partyId: '',
  businessType: '',
  taskInfo: {},
  tsarBreakDownConifg: [],
  monthPeriod: 'ALL',
  multipleOverallSideBarInfoController: null,
  exclusionMap: [],
};
