export default {
  visible: false,
  selectClient: '',
  selectQuestionnaire: '',
  roleByClientMap: {},
  sectionMap: {},
  customerQuestionnaireList: [],
  error: {},
  validating: false,
  processData: [],
  entities: {},
  otherPayload: {},
  isNB: false,
  isAgentName: false,
  hiddenHeaderForm: true,
};
