const previewData = {
  previewModeShow: false,
  previewResolve: null,
  previewModeData: {},
  previewSelectLetter: 0, //letter的index
  previewEnclosure: {},
  previewSelectEnclosureIndex: null, //attachment的index
  previewSelectEnclosureEdit: false, //当前是否是pdf编辑模式
  isChange: false,
  title: null,
  previewModePageAtomConfig: [],
  previewForm: {},
  previewCurrentReason: {},
  previewEditContent: {},
  previewUrl: '',
};
export { previewData };

export default {
  caseNo: '',
  businessNo: '',
  inquiryBusinessNo: '',
  taskStatus: '',
  reasonConfigs: [],
  activityKey: '',
  caseCategory: '',
  taskId: '',
  currentReasonGroups: [],
  activedGroupKey: null,
  currentReasonGroupsBackup: [],
  historyGroupKey: null,
  historyReasonGroups: [],
  destRoleInfo: {},
  thPendPolicyReasonInfo: {},
  policyNoInfo: {},
  paymentNoArr: [],
  isPending: false,
  allDocumentTypes: [],
  attachDocArr: [],
  form: {},
  errorInfo: {},
  caseCategoryReasonConfigs: [],
  listMemos: {},
  listMemoSubType: {},
  reasonHaveMemoSubType: {},
  historyChangeTime: null,
  sendDataIdArr: [],
  viewReasonInfo: [],
  reminderIndex: '0',
  batchEnvoySelected: [],
  requestClientInfoList: [],
  retryListGroups: {},
  getProcessJobInfoTimeStamp: '',
  ...previewData,
};
