export const BankAccount = {
  accountHolder: '',
  accountType: '',
  accountingSubject: '',
  bankAccountNo: '',
  bankCode: '',
  bankName: '',
  branchCode: '',
  branchName: '',
  claimNo: '',
  creator: '',
  id: '',
  modifier: '',
  passbookCode: '',
  passbookNo: '',
  payeeId: '',
  sourceBank: '',
  transId: '',
};
