import React from 'react';
import { FormSection, FormItemCascader } from 'basic/components/Form';
const dicts = [
  {
    id: null,
    creator: null,
    gmtCreate: null,
    modifier: null,
    gmtModified: null,
    deleted: null,
    transId: null,
    organizationCode: 'ORG00601',
    organizationName: 'Call Center',
    parentOrganizationCode: '',
    organizationLevel: null,
    organizationDesc: null,
    owner: null,
    type: null,
    effectiveDate: null,
    expiredDate: null,
    parent: null,
    children: null,
  },
  {
    id: null,
    creator: null,
    gmtCreate: null,
    modifier: null,
    gmtModified: null,
    deleted: null,
    transId: null,
    organizationCode: 'ORG_JP_Claim',
    organizationName: '保険金部',
    parentOrganizationCode: '-9999',
    organizationLevel: null,
    organizationDesc: null,
    owner: null,
    type: null,
    effectiveDate: null,
    expiredDate: null,
    parent: null,
    children: null,
  },
  {
    id: null,
    creator: null,
    gmtCreate: null,
    modifier: null,
    gmtModified: null,
    deleted: null,
    transId: null,
    organizationCode: 'ORG00501',
    organizationName: 'IT & Ops Governance',
    parentOrganizationCode: '',
    organizationLevel: null,
    organizationDesc: null,
    owner: null,
    type: null,
    effectiveDate: null,
    expiredDate: null,
    parent: null,
    children: null,
  },
  {
    id: null,
    creator: null,
    gmtCreate: null,
    modifier: null,
    gmtModified: null,
    deleted: null,
    transId: null,
    organizationCode: 'ORG00000',
    organizationName: 'Operation Department',
    parentOrganizationCode: 'ORG99999',
    organizationLevel: null,
    organizationDesc: null,
    owner: null,
    type: null,
    effectiveDate: null,
    expiredDate: null,
    parent: null,
    children: [
      {
        id: null,
        creator: null,
        gmtCreate: null,
        modifier: null,
        gmtModified: null,
        deleted: null,
        transId: null,
        organizationCode: 'ORG00001',
        organizationName: 'CTOO',
        parentOrganizationCode: 'ORG00000',
        organizationLevel: null,
        organizationDesc: null,
        owner: null,
        type: null,
        effectiveDate: null,
        expiredDate: null,
        parent: null,
        children: [
          {
            id: null,
            creator: null,
            gmtCreate: null,
            modifier: null,
            gmtModified: null,
            deleted: null,
            transId: null,
            organizationCode: 'ORG00002',
            organizationName: 'Ops Division ',
            parentOrganizationCode: 'ORG00001',
            organizationLevel: null,
            organizationDesc: null,
            owner: null,
            type: null,
            effectiveDate: null,
            expiredDate: null,
            parent: null,
            children: [
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORG00100',
                organizationName: 'Claim Department',
                parentOrganizationCode: 'ORG00002',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
            ],
          },
        ],
      },
      {
        id: null,
        creator: null,
        gmtCreate: null,
        modifier: null,
        gmtModified: null,
        deleted: null,
        transId: null,
        organizationCode: 'ORG00101',
        organizationName: 'FWD Thailand Bangkok',
        parentOrganizationCode: 'ORG00000',
        organizationLevel: null,
        organizationDesc: null,
        owner: null,
        type: null,
        effectiveDate: null,
        expiredDate: null,
        parent: null,
        children: [
          {
            id: null,
            creator: null,
            gmtCreate: null,
            modifier: null,
            gmtModified: null,
            deleted: null,
            transId: null,
            organizationCode: 'ORG00204',
            organizationName: 'ISC Team',
            parentOrganizationCode: 'ORG00101',
            organizationLevel: null,
            organizationDesc: null,
            owner: null,
            type: null,
            effectiveDate: null,
            expiredDate: null,
            parent: null,
            children: null,
          },
          {
            id: null,
            creator: null,
            gmtCreate: null,
            modifier: null,
            gmtModified: null,
            deleted: null,
            transId: null,
            organizationCode: 'ORG00201',
            organizationName: 'Sales Marketing',
            parentOrganizationCode: 'ORG00101',
            organizationLevel: null,
            organizationDesc: null,
            owner: null,
            type: null,
            effectiveDate: null,
            expiredDate: null,
            parent: null,
            children: null,
          },
          {
            id: null,
            creator: null,
            gmtCreate: null,
            modifier: null,
            gmtModified: null,
            deleted: null,
            transId: null,
            organizationCode: 'ORG00202',
            organizationName: 'Claim Department',
            parentOrganizationCode: 'ORG00101',
            organizationLevel: null,
            organizationDesc: null,
            owner: null,
            type: null,
            effectiveDate: null,
            expiredDate: null,
            parent: null,
            children: [
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORGTH00301',
                organizationName: 'TH Claim Admin',
                parentOrganizationCode: 'ORG00202',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORGTH00302',
                organizationName: 'TH Assessor',
                parentOrganizationCode: 'ORG00202',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORG00301',
                organizationName: 'Claim Data Capture',
                parentOrganizationCode: 'ORG00202',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORG00302',
                organizationName: 'Claim Assessment',
                parentOrganizationCode: 'ORG00202',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORG00303',
                organizationName: 'Manual Assessment',
                parentOrganizationCode: 'ORG00202',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
              {
                id: null,
                creator: null,
                gmtCreate: null,
                modifier: null,
                gmtModified: null,
                deleted: null,
                transId: null,
                organizationCode: 'ORG00304',
                organizationName: 'Claim Approval',
                parentOrganizationCode: 'ORG00202',
                organizationLevel: null,
                organizationDesc: null,
                owner: null,
                type: null,
                effectiveDate: null,
                expiredDate: null,
                parent: null,
                children: null,
              },
            ],
          },
          {
            id: null,
            creator: null,
            gmtCreate: null,
            modifier: null,
            gmtModified: null,
            deleted: null,
            transId: null,
            organizationCode: 'ORG00203',
            organizationName: 'Policy Administration',
            parentOrganizationCode: 'ORG00101',
            organizationLevel: null,
            organizationDesc: null,
            owner: null,
            type: null,
            effectiveDate: null,
            expiredDate: null,
            parent: null,
            children: null,
          },
        ],
      },
      {
        id: null,
        creator: null,
        gmtCreate: null,
        modifier: null,
        gmtModified: null,
        deleted: null,
        transId: null,
        organizationCode: 'ORG00401',
        organizationName: 'Test04',
        parentOrganizationCode: 'ORG00000',
        organizationLevel: null,
        organizationDesc: null,
        owner: null,
        type: null,
        effectiveDate: null,
        expiredDate: null,
        parent: null,
        children: null,
      },
    ],
  },
  {
    id: null,
    creator: null,
    gmtCreate: null,
    modifier: null,
    gmtModified: null,
    deleted: null,
    transId: null,
    organizationCode: 'Test01',
    organizationName: 'FWD Guangzhou Branch',
    parentOrganizationCode: '',
    organizationLevel: null,
    organizationDesc: null,
    owner: null,
    type: null,
    effectiveDate: null,
    expiredDate: null,
    parent: null,
    children: [
      {
        id: null,
        creator: null,
        gmtCreate: null,
        modifier: null,
        gmtModified: null,
        deleted: null,
        transId: null,
        organizationCode: 'Test02',
        organizationName: 'Technology',
        parentOrganizationCode: 'Test01',
        organizationLevel: null,
        organizationDesc: null,
        owner: null,
        type: null,
        effectiveDate: null,
        expiredDate: null,
        parent: null,
        children: [
          {
            id: null,
            creator: null,
            gmtCreate: null,
            modifier: null,
            gmtModified: null,
            deleted: null,
            transId: null,
            organizationCode: 'Test03',
            organizationName: 'IT Claim',
            parentOrganizationCode: 'Test02',
            organizationLevel: null,
            organizationDesc: null,
            owner: null,
            type: null,
            effectiveDate: null,
            expiredDate: null,
            parent: null,
            children: null,
          },
        ],
      },
    ],
  },
];
export default ({ form }: any) => {
  return (
    <>
      <FormSection title="FormItemCascader" layConf={12} isMargin={false}>
        <FormItemCascader
          form={form}
          required
          name="organization"
          formName="FormItemCascader"
          labelId="Organization"
          labelTypeCode="Label_COM_General"
          dicts={dicts}
          fieldNames={{
            label: 'organizationName',
            value: 'organizationCode',
            children: 'children',
          }}
        />
      </FormSection>
    </>
  );
};
