import { renderHook } from '@testing-library/react-hooks';
import useHandleChangeNumberOfUnitsCallback from 'process/NB/ManualUnderwriting/_hooks/useHandleChangeNumberOfUnitsCallback';

jest.mock('process/NB/ManualUnderwriting/_hooks/useGetCurrentCoverageIsMain', () => {
  return jest
    .fn(() => {
      return 'N';
    })
    .mockImplementationOnce(() => {
      return 'Y';
    });
});

jest.mock('process/NB/ManualUnderwriting/_hooks/useGetCoverageDataSource', () => {
  return jest
    .fn(() => {
      return [];
    })
    .mockImplementationOnce(() => {
      return [
        {
          id: '092a4c4e-199c-498e-9474-f2c622e25250',
          creator: 'SYSTEM',
          gmtCreate: '2023-08-11T07:15:57.000+0000',
          modifier: '0',
          gmtModified: '2023-08-11T07:15:57.000+0000',
          deleted: 0,
          transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
          applicationNo: 'TM2023081018',
          policyId: 'ZDH00003',
          coverageNum: '1',
          isMain: 'Y',
          embedFlag: '1',
          planCategory: '2222',
          productCode: 'RO31',
          productName: 'Bebas Rencana Optimal - 10 yrs',
          coreCode: 'RO31',
          timeRiskMark: '1',
          isBack: '',
          isExemptions: '0',
          isExempt: '0',
          indemnifyPeriod: '10',
          indemnifyPeriodUnit: 'Y',
          payPeriod: '5',
          payPeriodUnit: 'Y',
          sumAssured: 100000000,
          unit: null,
          premiumMode: 'A',
          basePremium: 0,
          loadingPremium: null,
          loadedPremium: 0,
          discount: 0,
          grossPremium: 0,
          tax: '0',
          taxAmount: 0,
          rspPremiumTerm: '2',
          instalmentPremiumWithTax: 0,
          riskType: 'LIFE',
          priority: '0',
          compareSeq: '0',
          annualPrem: 0,
          monthlyPrem: 0,
          quarterlyPrem: 0,
          semiAnnualPrem: 0,
          annualizedPrem: 0,
          underwritingType: 'GIO',
          packageId: '122',
          packageCode: '12',
          planBusinessCode: 'RO31',
          planName: 'Bebas Rencana Optimal',
          laCategory: '122',
          backDay: 0,
          pbCodes: '12222',
          matureDate: '2021-12-12T00:00:00.000+0000',
          occupationType: 'A',
          occupationRate: '122',
          rsp: '1',
          rspCharge: '1',
          unionInsuredSeqNum: '1',
          benefitSubType: 'TAFL',
          pid: 'ABRO',
          productType: 'T',
          productLine: 'MED',
          upToAge: null,
          lifeNo: '01',
          jointLifeNo: null,
          coverageNo: '01',
          riderNo: '00',
          payerIndicator: 'N',
          embedIndicator: 'N',
          premiumTermType: null,
          componentDescriptionEn: null,
          componentDescriptionLocal: null,
          hospitalPlanCode: null,
          discountRate: null,
          discountType: null,
          customerSegment: null,
          sinceCertificateYear: null,
          stampDuty: null,
          initialPrem: null,
          indemnifyAgePeriod: null,
          payAgePeriod: null,
          systemAutoAddInd: null,
          laPremium: null,
          planMedexSmre: null,
          saWaiver: null,
          notManualRemove: null,
          occupationLoading: null,
          calculateBy: null,
          originalCoi: null,
          finalCoi: null,
          extraCoi: null,
          withdrawalTerm: null,
          annuityTerm: null,
          retirementTerm: null,
          guaranteedMonthlyPayout: null,
          sumAssuredWaive: null,
          loadingPremiumWaive: null,
          instalmentPremiumWithTaxWaive: null,
          hasLoading: null,
          returnOfPremium: null,
          originalInstalmentPremiumWithTax: 0,
          originalGrossPremium: 0,
          originalBasePremium: 0,
          originalInitialPrem: null,
          originalAnnualPrem: 0,
          originalLaPremium: null,
          sumAssuredMultiplier: null,
          coverageInsuredList: [
            {
              id: '10e02563-3cb2-494e-8049-d8c13912183a',
              creator: 'SYSTEM',
              gmtCreate: '2023-08-11T07:15:57.000+0000',
              modifier: '0',
              gmtModified: '2023-08-11T07:15:57.000+0000',
              deleted: 0,
              transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
              applicationNo: 'TM2023081018',
              policyId: 'ZDH00003',
              coverageId: '092a4c4e-199c-498e-9474-f2c622e25250',
              clientId: '7cdddb66-6979-4570-84b3-888a21401551',
              insuredSeqNum: '1',
              insuredIndex: '0',
              insuredNum: '1',
              clientName: '',
            },
          ],
          coverageFundInfoList: [],
          coverageDecision: null,
          initialCoverageDecision: null,
          coverageExclusionList: null,
          initialCoverageExclusionList: null,
          coverageRemarkList: null,
          coverageLoadingList: null,
          initialCoverageLoadingList: null,
          evidenceList: null,
          initialEvidenceList: null,
          fundVisible: false,
          currencyCode: 'IDR',
          loadingRule: {
            id: 'e5fff9c7-f860-4ad4-b5cb-88bf3c459a9c',
            creator: 'GZOBLX',
            gmtCreate: '2022-11-21T09:00:00.000+0000',
            modifier: 'GZOBLX',
            gmtModified: '2022-11-21T09:00:00.000+0000',
            deleted: 0,
            transId: 'ccf62ac5-7394-4283-a85d-a697df8f4bea',
            regionCode: 'ID',
            productCode: 'RO31',
            addLoading: null,
            meAllowIndicator: 'N',
            meMin: null,
            meMax: null,
            feAllowIndicator: 'Y',
            feMin: 25,
            feMax: 400,
            rateAllowIndicator: 'Y',
            rateMin: 100,
            rateMax: 500,
            includeRiderLoadingInd: null,
            meTermFollowCode: 'PT',
            feTermFollowCode: 'PT',
            rateTermFollowCode: 'RT',
          },
          loanInfoList: null,
          coverageBenefitsList: [
            {
              id: 'b81995a6-bb2d-4e0a-a8d3-0e21a9d63afb',
              creator: 'SYSTEM',
              gmtCreate: '2023-08-11T07:15:57.000+0000',
              modifier: '0',
              gmtModified: '2023-08-11T07:15:57.000+0000',
              deleted: 0,
              transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
              applicationNo: 'TM2023081018',
              coverageId: '092a4c4e-199c-498e-9474-f2c622e25250',
              policyId: 'ZDH00003',
              type: null,
              subType: null,
              priority: '0',
              compareSeq: '0',
              benefitDealMode: '',
              benefitDrawMode: '',
              premiumType: '',
              benefitAssured: 10000,
            },
          ],
          sustainabilityChecking: null,
          fundChartDataUrl: null,
          waiveProductList: null,
          numberOfUnits: null,
          subProductType: '',
          annualLimit: null,
          productCategory: null,
          benefitPlanEditInd: null,
          underwritingApproach: null,
          showRop: false,
        },
        {
          id: '926c7783-f373-4255-bc01-d52fafa4eeb8',
          creator: 'SYSTEM',
          gmtCreate: '2023-08-11T07:15:57.000+0000',
          modifier: '0',
          gmtModified: '2023-08-11T07:15:57.000+0000',
          deleted: 0,
          transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
          applicationNo: 'TM2023081018',
          policyId: 'ZDH00003',
          coverageNum: '2',
          isMain: 'N',
          embedFlag: '1',
          planCategory: '2222',
          productCode: 'ADB5',
          productName: 'ROP Acc Death Benef BN-10 yrs',
          coreCode: 'ADB5',
          timeRiskMark: '1',
          isBack: '',
          isExemptions: '0',
          isExempt: '0',
          indemnifyPeriod: '10',
          indemnifyPeriodUnit: 'Y',
          payPeriod: '5',
          payPeriodUnit: 'Y',
          sumAssured: 40000000,
          unit: null,
          premiumMode: 'A',
          basePremium: 0,
          loadingPremium: null,
          loadedPremium: 0,
          discount: 0,
          grossPremium: 0,
          tax: '0',
          taxAmount: 0,
          rspPremiumTerm: '2',
          instalmentPremiumWithTax: 0,
          riskType: null,
          priority: null,
          compareSeq: '0',
          annualPrem: 0,
          monthlyPrem: 0,
          quarterlyPrem: 0,
          semiAnnualPrem: 0,
          annualizedPrem: 0,
          underwritingType: 'GIO',
          packageId: '122',
          packageCode: '12',
          planBusinessCode: 'ADB5',
          planName: 'ROP Acc Death Benef BN-10 yrs',
          laCategory: '122',
          backDay: 0,
          pbCodes: '12222',
          matureDate: '2021-12-12T00:00:00.000+0000',
          occupationType: 'A',
          occupationRate: '122',
          rsp: '1',
          rspCharge: '1',
          unionInsuredSeqNum: '1',
          benefitSubType: null,
          pid: 'ADB',
          productType: 'ILP',
          productLine: 'TERM',
          upToAge: null,
          lifeNo: '01',
          jointLifeNo: null,
          coverageNo: '01',
          riderNo: '01',
          payerIndicator: 'N',
          embedIndicator: 'Y',
          premiumTermType: null,
          componentDescriptionEn: null,
          componentDescriptionLocal: null,
          hospitalPlanCode: null,
          discountRate: null,
          discountType: null,
          customerSegment: null,
          sinceCertificateYear: null,
          stampDuty: null,
          initialPrem: null,
          indemnifyAgePeriod: null,
          payAgePeriod: null,
          systemAutoAddInd: null,
          laPremium: null,
          planMedexSmre: null,
          saWaiver: null,
          notManualRemove: null,
          occupationLoading: null,
          calculateBy: null,
          originalCoi: null,
          finalCoi: null,
          extraCoi: null,
          withdrawalTerm: null,
          annuityTerm: null,
          retirementTerm: null,
          guaranteedMonthlyPayout: null,
          sumAssuredWaive: null,
          loadingPremiumWaive: null,
          instalmentPremiumWithTaxWaive: null,
          hasLoading: null,
          returnOfPremium: null,
          originalInstalmentPremiumWithTax: 0,
          originalGrossPremium: 0,
          originalBasePremium: 0,
          originalInitialPrem: null,
          originalAnnualPrem: 0,
          originalLaPremium: null,
          sumAssuredMultiplier: null,
          coverageInsuredList: [
            {
              id: 'e8cbb04d-0f3a-4b13-a46b-018cb905288f',
              creator: 'SYSTEM',
              gmtCreate: '2023-08-11T07:15:57.000+0000',
              modifier: '0',
              gmtModified: '2023-08-11T07:15:57.000+0000',
              deleted: 0,
              transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
              applicationNo: 'TM2023081018',
              policyId: 'ZDH00003',
              coverageId: '926c7783-f373-4255-bc01-d52fafa4eeb8',
              clientId: '7cdddb66-6979-4570-84b3-888a21401551',
              insuredSeqNum: '1',
              insuredIndex: '0',
              insuredNum: '1',
              clientName: '',
            },
          ],
          coverageFundInfoList: [],
          coverageDecision: null,
          initialCoverageDecision: null,
          coverageExclusionList: null,
          initialCoverageExclusionList: null,
          coverageRemarkList: null,
          coverageLoadingList: null,
          initialCoverageLoadingList: null,
          evidenceList: null,
          initialEvidenceList: null,
          fundVisible: false,
          currencyCode: 'IDR',
          loadingRule: {
            id: '6f3dbc19-2489-4245-9ba0-485807e753b1',
            creator: 'GZOBLX',
            gmtCreate: '2022-11-21T09:00:00.000+0000',
            modifier: 'GZOBLX',
            gmtModified: '2022-11-21T09:00:00.000+0000',
            deleted: 0,
            transId: 'ccf62ac5-7394-4283-a85d-a697df8f4bea',
            regionCode: 'ID',
            productCode: 'ADB5',
            addLoading: null,
            meAllowIndicator: 'N',
            meMin: null,
            meMax: null,
            feAllowIndicator: 'N',
            feMin: null,
            feMax: null,
            rateAllowIndicator: 'N',
            rateMin: null,
            rateMax: null,
            includeRiderLoadingInd: null,
            meTermFollowCode: null,
            feTermFollowCode: null,
            rateTermFollowCode: null,
          },
          loanInfoList: null,
          coverageBenefitsList: null,
          sustainabilityChecking: null,
          fundChartDataUrl: null,
          waiveProductList: null,
          numberOfUnits: null,
          subProductType: null,
          annualLimit: null,
          productCategory: null,
          benefitPlanEditInd: null,
          underwritingApproach: null,
          showRop: false,
        },
        {
          id: 'a54ef6a5-421e-44db-a822-a6c12e05895b',
          creator: 'SYSTEM',
          gmtCreate: '2023-08-11T07:15:57.000+0000',
          modifier: '0',
          gmtModified: '2023-08-11T07:15:57.000+0000',
          deleted: 0,
          transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
          applicationNo: 'TM2023081018',
          policyId: 'ZDH00003',
          coverageNum: '3',
          isMain: 'N',
          embedFlag: '1',
          planCategory: '2222',
          productCode: 'ADD1',
          productName: 'ROP Acc Dth & Dis Benef 10 yrs',
          coreCode: 'ADD1',
          timeRiskMark: '1',
          isBack: '',
          isExemptions: '0',
          isExempt: '0',
          indemnifyPeriod: '10',
          indemnifyPeriodUnit: 'Y',
          payPeriod: '5',
          payPeriodUnit: 'Y',
          sumAssured: 100000000,
          unit: null,
          premiumMode: 'A',
          basePremium: 0,
          loadingPremium: null,
          loadedPremium: 0,
          discount: 0,
          grossPremium: 0,
          tax: '0',
          taxAmount: 0,
          rspPremiumTerm: '2',
          instalmentPremiumWithTax: 0,
          riskType: 'ADB',
          priority: '0',
          compareSeq: '0',
          annualPrem: 0,
          monthlyPrem: 0,
          quarterlyPrem: 0,
          semiAnnualPrem: 0,
          annualizedPrem: 0,
          underwritingType: 'GIO',
          packageId: '122',
          packageCode: '12',
          planBusinessCode: 'ADD1',
          planName: 'ROP Acc Dth & Dis Benef 10 yrs',
          laCategory: '122',
          backDay: 0,
          pbCodes: '12222',
          matureDate: '2021-12-12T00:00:00.000+0000',
          occupationType: 'A',
          occupationRate: '122',
          rsp: '1',
          rspCharge: '1',
          unionInsuredSeqNum: '1',
          benefitSubType: 'TADB',
          pid: 'ADD',
          productType: 'T',
          productLine: 'TERM',
          upToAge: null,
          lifeNo: '01',
          jointLifeNo: null,
          coverageNo: '01',
          riderNo: '02',
          payerIndicator: 'N',
          embedIndicator: 'Y',
          premiumTermType: null,
          componentDescriptionEn: null,
          componentDescriptionLocal: null,
          hospitalPlanCode: null,
          discountRate: null,
          discountType: null,
          customerSegment: null,
          sinceCertificateYear: null,
          stampDuty: null,
          initialPrem: null,
          indemnifyAgePeriod: null,
          payAgePeriod: null,
          systemAutoAddInd: null,
          laPremium: null,
          planMedexSmre: null,
          saWaiver: null,
          notManualRemove: null,
          occupationLoading: null,
          calculateBy: null,
          originalCoi: null,
          finalCoi: null,
          extraCoi: null,
          withdrawalTerm: null,
          annuityTerm: null,
          retirementTerm: null,
          guaranteedMonthlyPayout: null,
          sumAssuredWaive: null,
          loadingPremiumWaive: null,
          instalmentPremiumWithTaxWaive: null,
          hasLoading: null,
          returnOfPremium: null,
          originalInstalmentPremiumWithTax: 0,
          originalGrossPremium: 0,
          originalBasePremium: 0,
          originalInitialPrem: null,
          originalAnnualPrem: 0,
          originalLaPremium: null,
          sumAssuredMultiplier: null,
          coverageInsuredList: [
            {
              id: '0cb25343-9fdb-42a5-8a3c-e243ec3f945d',
              creator: 'SYSTEM',
              gmtCreate: '2023-08-11T07:15:57.000+0000',
              modifier: '0',
              gmtModified: '2023-08-11T07:15:57.000+0000',
              deleted: 0,
              transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
              applicationNo: 'TM2023081018',
              policyId: 'ZDH00003',
              coverageId: 'a54ef6a5-421e-44db-a822-a6c12e05895b',
              clientId: '7cdddb66-6979-4570-84b3-888a21401551',
              insuredSeqNum: '1',
              insuredIndex: '0',
              insuredNum: '1',
              clientName: '',
            },
          ],
          coverageFundInfoList: [],
          coverageDecision: null,
          initialCoverageDecision: null,
          coverageExclusionList: null,
          initialCoverageExclusionList: null,
          coverageRemarkList: null,
          coverageLoadingList: null,
          initialCoverageLoadingList: null,
          evidenceList: null,
          initialEvidenceList: null,
          fundVisible: false,
          currencyCode: 'IDR',
          loadingRule: {
            id: 'd516ccb9-ee7d-4c60-be6c-3e7cbaf19f5a',
            creator: 'GZOBLX',
            gmtCreate: '2022-11-21T09:00:00.000+0000',
            modifier: 'GZOBLX',
            gmtModified: '2022-11-21T09:00:00.000+0000',
            deleted: 0,
            transId: 'ccf62ac5-7394-4283-a85d-a697df8f4bea',
            regionCode: 'ID',
            productCode: 'ADD1',
            addLoading: 'N',
            meAllowIndicator: 'N',
            meMin: null,
            meMax: null,
            feAllowIndicator: 'N',
            feMin: 0,
            feMax: 0,
            rateAllowIndicator: 'N',
            rateMin: 0,
            rateMax: 0,
            includeRiderLoadingInd: null,
            meTermFollowCode: null,
            feTermFollowCode: null,
            rateTermFollowCode: null,
          },
          loanInfoList: null,
          coverageBenefitsList: null,
          sustainabilityChecking: null,
          fundChartDataUrl: null,
          waiveProductList: null,
          numberOfUnits: null,
          subProductType: null,
          annualLimit: null,
          productCategory: null,
          benefitPlanEditInd: null,
          underwritingApproach: null,
          showRop: false,
        },
        {
          id: '64685efe-1828-4cfe-b9ca-b2ceef22f092',
          creator: 'SYSTEM',
          gmtCreate: '2023-08-11T07:15:57.000+0000',
          modifier: '0',
          gmtModified: '2023-08-11T07:15:57.000+0000',
          deleted: 0,
          transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
          applicationNo: 'TM2023081018',
          policyId: 'ZDH00003',
          coverageNum: '4',
          isMain: 'N',
          embedFlag: '1',
          planCategory: '2222',
          productCode: 'ADO1',
          productName: 'ROP Acc Death Benef PH-10 yrs',
          coreCode: 'ADO1',
          timeRiskMark: '1',
          isBack: '',
          isExemptions: '0',
          isExempt: '0',
          indemnifyPeriod: '10',
          indemnifyPeriodUnit: 'Y',
          payPeriod: '5',
          payPeriodUnit: 'Y',
          sumAssured: 40000000,
          unit: null,
          premiumMode: 'A',
          basePremium: 0,
          loadingPremium: null,
          loadedPremium: 0,
          discount: 0,
          grossPremium: 0,
          tax: '0',
          taxAmount: 0,
          rspPremiumTerm: '2',
          instalmentPremiumWithTax: 0,
          riskType: null,
          priority: '0',
          compareSeq: '0',
          annualPrem: 0,
          monthlyPrem: 0,
          quarterlyPrem: 0,
          semiAnnualPrem: 0,
          annualizedPrem: 0,
          underwritingType: 'GIO',
          packageId: '122',
          packageCode: '12',
          planBusinessCode: 'ADO1',
          planName: 'ROP Acc Death Benef PH-10 yrs',
          laCategory: '122',
          backDay: 0,
          pbCodes: '12222',
          matureDate: '2021-12-12T00:00:00.000+0000',
          occupationType: 'A',
          occupationRate: '122',
          rsp: '1',
          rspCharge: '1',
          unionInsuredSeqNum: '2',
          benefitSubType: null,
          pid: 'ADO',
          productType: 'T',
          productLine: 'TERM',
          upToAge: null,
          lifeNo: '01',
          jointLifeNo: null,
          coverageNo: '01',
          riderNo: '03',
          payerIndicator: 'Y',
          embedIndicator: 'Y',
          premiumTermType: null,
          componentDescriptionEn: null,
          componentDescriptionLocal: null,
          hospitalPlanCode: null,
          discountRate: null,
          discountType: null,
          customerSegment: null,
          sinceCertificateYear: null,
          stampDuty: null,
          initialPrem: null,
          indemnifyAgePeriod: null,
          payAgePeriod: null,
          systemAutoAddInd: null,
          laPremium: null,
          planMedexSmre: null,
          saWaiver: null,
          notManualRemove: null,
          occupationLoading: null,
          calculateBy: null,
          originalCoi: null,
          finalCoi: null,
          extraCoi: null,
          withdrawalTerm: null,
          annuityTerm: null,
          retirementTerm: null,
          guaranteedMonthlyPayout: null,
          sumAssuredWaive: null,
          loadingPremiumWaive: null,
          instalmentPremiumWithTaxWaive: null,
          hasLoading: null,
          returnOfPremium: null,
          originalInstalmentPremiumWithTax: 0,
          originalGrossPremium: 0,
          originalBasePremium: 0,
          originalInitialPrem: null,
          originalAnnualPrem: 0,
          originalLaPremium: null,
          sumAssuredMultiplier: null,
          coverageInsuredList: [
            {
              id: '00894762-c41e-4d2e-aec6-11fb64a3f613',
              creator: 'SYSTEM',
              gmtCreate: '2023-08-11T07:15:57.000+0000',
              modifier: '0',
              gmtModified: '2023-08-11T07:15:57.000+0000',
              deleted: 0,
              transId: 'f4a1dc55-57cd-49e1-99b8-c7c8474f5f05',
              applicationNo: 'TM2023081018',
              policyId: 'ZDH00003',
              coverageId: '64685efe-1828-4cfe-b9ca-b2ceef22f092',
              clientId: '7cdddb66-6979-4570-84b3-888a21401551',
              insuredSeqNum: '1',
              insuredIndex: null,
              insuredNum: '1',
              clientName: '',
            },
          ],
          coverageFundInfoList: [],
          coverageDecision: null,
          initialCoverageDecision: null,
          coverageExclusionList: null,
          initialCoverageExclusionList: null,
          coverageRemarkList: null,
          coverageLoadingList: null,
          initialCoverageLoadingList: null,
          evidenceList: null,
          initialEvidenceList: null,
          fundVisible: false,
          currencyCode: 'IDR',
          loadingRule: {
            id: 'eff83e4d-17bc-4cd2-aa8d-cbb7e3f7b7b2',
            creator: 'GZOBLX',
            gmtCreate: '2022-11-21T09:00:00.000+0000',
            modifier: 'GZOBLX',
            gmtModified: '2022-11-21T09:00:00.000+0000',
            deleted: 0,
            transId: 'ccf62ac5-7394-4283-a85d-a697df8f4bea',
            regionCode: 'ID',
            productCode: 'ADO1',
            addLoading: null,
            meAllowIndicator: 'N',
            meMin: null,
            meMax: null,
            feAllowIndicator: 'N',
            feMin: null,
            feMax: null,
            rateAllowIndicator: 'N',
            rateMin: null,
            rateMax: null,
            includeRiderLoadingInd: null,
            meTermFollowCode: null,
            feTermFollowCode: null,
            rateTermFollowCode: null,
          },
          loanInfoList: null,
          coverageBenefitsList: null,
          sustainabilityChecking: null,
          fundChartDataUrl: null,
          waiveProductList: null,
          numberOfUnits: null,
          subProductType: null,
          annualLimit: null,
          productCategory: null,
          benefitPlanEditInd: 'C',
          underwritingApproach: null,
          showRop: false,
        },
      ];
    });
});

let dispatchParams = {};
jest.mock('dva', () => {
  const actual = jest.requireActual('dva');
  return {
    ...actual,
    useDispatch: () => {
      return jest.fn((params: any) => {
        dispatchParams = params;
      });
    },
    useSelector: jest.fn(() => {
      return {
        otherPlanProductFeatureList: [
          {
            productCode: 'ADO1',
            benefitPlanEditInd: 'C',
          },
        ],
      };
    }),
  };
});

describe('useHandleChangeNumberOfUnitsCallback', () => {
  test('handle change main coverage plan option', () => {
    const renderer = renderHook(() =>
      useHandleChangeNumberOfUnitsCallback({
        id: '092a4c4e-199c-498e-9474-f2c622e25250',
        field: 'hospitalPlanCode',
      })
    );
    const handleChange = renderer.result.current;
    handleChange('ABC');

    expect(dispatchParams).toEqual({});
  });
});
