// 事故
const INCIDENTITEM = {
  // causeOfDeath: '',
  adjustCauseOfIncident: '',
  systemCauseOfIncident: '',
  causeOfIncident: '',
  claimNo: '',
  claimType: '',
  claimTypeArray: [],
  creator: '',
  // deathDate: null,
  deleted: 0,
  diagnosisList: [],
  gmtCreate: null,
  gmtModified: null,
  id: '',
  identificationDate: null,
  incidentDate: null,
  incidentInDetail: '',
  incidentNo: '',
  incidentPlace: '',
  // insuredType: '',
  modifier: '',
  orderNum: 0,
  partOfBodyInjured: '',
  partOfBodyInjuredArray: [],
  primaryDiagnosisCode: '',
  // requirementNo: '',
  transId: '',
  treatmentList: [],
  jpIncident: {},
  // waivedReason: '',
};
// 事故jp
const JPINCIDENTITEM = {
  aCauseOfDeath: '',
  bcauseOfA: '',
  causeOfDeath: '',
  ccauseOfB: '',
  certificateDate: null,
  cervicalCancerCin: '',
  claimNo: '',
  creator: '',
  meetDemand: '',
  deathDate: null,
  deleted: 0,
  disabilityDegreeDate: null,
  disabilityName: '',
  drinking: '',
  drivingLicense: '',
  gmtCreate: null,
  gmtModified: null,
  highlyDisabilityCode: '',
  id: '',
  incidentId: '',
  informationPerfectionDate: null,
  insuredType: '',
  laborConstrainedOfAmi: '',
  modifier: '',
  oneCauseOfC: '',
  periodFromAToDeath: '',
  periodFromBToDeath: '',
  periodFromCToDeath: '',
  periodFromOneToDeath: '',
  periodFromTwoToDeath: '',
  requirementNo: '',
  requiringNursingDate: null,
  sequelaeNameOfStroke: '',
  sequelaeOfStroke: '',
  transId: '',
  twoDiagnosisName: '',
  waivedReason: '',
};

// 诊断
const DIAGNOSISITEM = {
  claimNo: '',
  creator: '',
  criticalIllness: 0,
  criticalIllnessName: '',
  dateOfOnset: null,
  deleted: 0,
  diagnosisCode: '',
  determinationDate: null,
  diagnosisName: '',
  diagnosisNo: '',
  diagnosisType: '',
  diagnosticPathology: '01',
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  modifier: '',
  orderNum: 0,
  pathologicalName: '',
  transId: '',
  stdDiagnosisName: '',
  malignantNeoplasmType: '',
  depthOfColorectalCancer: '',
  firstDeterminationDate: null,
};
// 治疗
const TREATMENTITEM = {
  claimNo: '',
  creator: '',
  dateOfAdmission: null,
  dateOfConsultation: null,
  dateOfDischarge: null,
  deleted: 0,
  department: '',
  doctor: '',
  gmtCreate: null,
  gmtModified: null,
  icu: 0,
  icuDays: 0,
  icuFromDate: null,
  icuToDate: null,
  id: '',
  incidentId: '',
  invoiceList: [],
  jpMedicineTreatmentList: [],
  medicalProvider: '',
  modifier: '',
  otherProcedureList: [],
  patientNo: '',
  procedureList: [],
  transId: '',
  treatmentNo: '',
  treatmentType: '',
};
// 手术
const PROCEDUREITEM = {
  claimNo: '',
  creator: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  kjCode: '',
  modifier: '',
  operationDate: null,
  orderNum: 0,
  partOfBody: '',
  procedureCode: '',
  procedureName: '',
  reimbursementPercentage: null,
  transId: '',
  treatmentId: '',
  stdPocedureName: '',
};
// 先进医疗
const OTHERPROCEDUREITEM = {
  claimNo: '',
  creator: '',
  deleted: 0,
  expense: 0,
  fromDate: null,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  modifier: '',
  orderNum: 0,
  partOfBody: '',
  procedureCode: '',
  procedureName: '',
  procedureType: '',
  toDate: null,
  transId: '',
  treatmentId: '',
};
// 薬剤
const JPMEDICINETREATMENT = {
  claimNo: '',
  creator: '',
  deleted: 0,
  diagnosisName: '',
  gmtCreate: '',
  gmtModified: '',
  id: '',
  jpTreatmentDateList: [],
  medicineName: '',
  medicineTreatmentNo: 0,
  medicineTreatmentType: '',
  modifier: '',
  publicInsurance: '',
  publicInsuranceNo: '',
  transId: '',
  treatmentId: '',
};
// 治療履歴
const JPTREATMENTDATE = {
  claimNo: '',
  creator: '',
  deleted: 0,
  gmtCreate: '',
  gmtModified: '',
  id: '',
  medicineId: '',
  modifier: '',
  transId: '',
  treatmentDate: null,
  treatmentId: '',
};
// 发票
const INVOICEITEM = {
  claimNo: '',
  creator: '',
  deleted: 0,
  discount: null,
  expense: null,
  gmtCreate: null,
  gmtModified: null,
  grossExpense: 0,
  id: '',
  invoiceDate: null,
  invoiceNo: '',
  modifier: '',
  orderNum: 0,
  remark: '',
  serviceItemList: [],
  transId: '',
  treatmentId: '',
};
// 费用项
const SERVICEITEM = {
  claimNo: '',
  creator: '',
  deleted: 0,
  discount: null,
  expense: null,
  expensePerUnit: 1,
  fromDate: null,
  gmtCreate: null,
  gmtModified: null,
  grossExpense: 0,
  id: '',
  invoiceId: '',
  modifier: '',
  orderNum: 0,
  partOfBody: '',
  procedureItem: '',
  procedureType: '',
  serviceItem: '',
  toDate: null,
  transId: '',
  unit: null,
};
// 保单受益分配
const POLICYBENEFITITEM = {
  beneficiaryList: [],
  benefitAmount: 0,
  claimNo: '',
  creator: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  modifier: '',
  payablesType: '',
  policyHolder: '',
  policyNo: '',
  policyType: '',
  transId: '',
};
// 领款人
const PAYEEITEM = {
  account: '',
  address: '',
  bankAccountName: '',
  bankAccountNo: '',
  bankCode: '',
  branchCode: '',
  branchName: '',
  claimNo: '',
  creator: '',
  deleted: 0,
  email: '',
  firstName: '',
  gmtCreate: null,
  gmtModified: null,
  id: '',
  identityNo: '',
  identityType: '',
  modifier: '',
  organization: 0,
  passbookCode: '',
  passbookNo: '',
  payeeNo: '',
  payeeType: '',
  paymentAmount: 0,
  paymentMethod: '',
  phoneNo: '',
  postCode: '',
  relationshipWithInsured: '',
  scheduledDate: null,
  surname: '',
  transId: '',
  transferAccount: '',
  typeOfPayment: '',
};
// 受益人
const BENEFICIARYITEM = {
  address: '',
  beneficiaryAmount: 0,
  beneficiaryPercentage: 0,
  claimNo: '',
  creator: '',
  dateOfBirth: null,
  deleted: 0,
  email: '',
  firstName: '',
  gender: '',
  gmtCreate: null,
  gmtModified: null,
  id: '',
  identityNo: '',
  identityType: '',
  modifier: '',
  organization: 0,
  payee: '',
  payeeId: '',
  phoneNo: '',
  policyBenefitId: '',
  postCode: '',
  relationshipWithInsured: '',
  relationshipWithPayee: '',
  surname: '',
  transId: '',
};
// 事故层级的赔付金
const CLAIMPAYABLEITEM = {
  assessResultKey: '',
  assessorOverrideAmount: null,
  assessorOverridePercentage: null,
  assessorOverrideMultiple: null,
  benefitCategory: '',
  benefitTypeCode: '',
  causeOfIncident: '',
  claimDecision: 'A',
  claimNo: '',
  creator: '',
  declineCode: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentDate: null,
  incidentId: '',
  insuredId: '',
  lifePayable: null,
  modifier: '',
  manualAdd: '',
  payableAmount: 0,
  policyCategory: '',
  policyNo: '',
  policyYear: null,
  policySetupStatus: '',
  primaryDiagnosisCode: '',
  productCode: '',
  remark: '',
  systemCalculationAmount: 0,
  transId: '',
  treatmentPayableList: [],
};
// 寿险的赔付金
const LIFEPAYABLE = {
  amountType: '',
  assessorOverrideAmount: null,
  assessorOverridePercentage: null,
  assessorOverrideMultiple: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  calculationAmount: null,
  claimNo: '',
  creator: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  modifier: '',
  payableAmount: 0,
  payableId: '',
  policyNo: '',
  productCode: '',
  reimbursementPercentage: null,
  reimbursementMultiple: null,
  remark: '',
  systemCalculationAmount: 0,
  transId: '',
};
// 治疗层级的赔付金
const TREATMENTPAYABLEITEM = {
  assessorOverrideAmount: null,
  assessorOverrideDays: null,
  assessorOverrideDeductible: null,
  assessorOverridePercentage: null,
  assessorOverrideMultiple: null,
  benefitAmount: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  claimNo: '',
  creator: '',
  dateOfAdmission: null,
  dateOfConsultation: null,
  dateOfDischarge: null,
  deductibleAmount: null,
  deductibleDays: null,
  deleted: 0,
  expenseAmount: null,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  invoicePayableList: [],
  modifier: '',
  payableAmount: null,
  payableDays: null,
  payableId: '',
  policyNo: '',
  process: [],
  productCode: '',
  reimbursementPercentage: null,
  reimbursementMultiple: null,
  remark: '',
  systemCalculationAmount: 0,
  transId: '',
  treatmentId: '',
};

const MAINBENEFITITEM = {
  claimNo: '',
  creator: '',
  deleted: 0,
  doctor: '',
  gmtCreate: null,
  gmtModified: null,
  id: '',
  mainBenefit: '',
  modifier: '',
  orderNum: 0,
  transId: '',
  treatmentId: '',
};

// 账单层级的赔付金
const INVOICEPAYABLEITEM = {
  assessorOverrideAmount: null,
  benefitTypeCode: '',
  claimNo: '',
  creator: '',
  deleted: 0,
  expenseAmount: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  invoiceId: '',
  modifier: '',
  payableAmount: null,
  payableId: '',
  policyNo: '',
  productCode: '',
  serviceItemPayableList: [],
  systemCalculationAmount: 0,
  transId: '',
  treatmentId: '',
  treatmentPayableId: '',
  benefitItemPayableList: [],
};
// 费用项层级的赔付金
const SERVICEPAYABLEITEM = {
  assessorOverrideAmount: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  calculationAmount: 0,
  calculationDays: 0,
  calculationPerDay: 0,
  claimNo: '',
  coInsuranceAmount: 0,
  creator: '',
  deductibleAmount: 0,
  deleted: 0,
  expenseAmount: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  invoiceId: '',
  invoicePayableId: '',
  modifier: '',
  payableAmount: 0,
  payableDays: 0,
  payableId: '',
  payablePerDay: 0,
  policyNo: '',
  process: [],
  productCode: '',
  remark: '',
  serviceItem: '',
  serviceItemId: '',
  systemCalculationAmount: 0,
  transId: '',
  treatmentId: '',
  treatmentPayableId: '',
};

const PAYEEINFO = {
  payeeType: '',
  firstName: '',
  surname: '',
  identityType: '',
  identityNo: '',
  phoneNo: '',
  relationshipWithInsured: '',
  organization: 0,
  paymentMethod: '',
  id: '',
};

const BENEFITITEMPAYABLEITEM = {
  id: '',
  claimNo: '',
  payableId: '',
  treatmentPayableId: '',
  invoicePayableId: '',
  incidentId: '',
  treatmentId: '',
  invoiceId: '',
  policyNo: '',
  productCode: '',
  benefitTypeCode: '',
  benefitItemCode: '',
  expenseAmount: null,
  deductibleAmount: null,
  calculationAmount: null,
  calculationDays: null,
  payableDays: null,
  coInsuranceAmount: null,
  insurerCoInsuranceAmount: null,
  payableAmount: null,
  remark: '',
  systemCalculationAmount: null,
  assessorOverrideAmount: null,
  calculationPerDay: null,
  payablePerDay: null,
  uncoverAmount: null,
  serviceItems: '',
};

const ACCIDENT_BENEFIT_PAYABLE_ITEM = {
  maxAmountPerWeek: null,
  amountPerWeek: null,
  assessorOverrideAmount: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  claimDecision: '',
  claimNo: '',
  creator: '',
  declineCode: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  modifier: '',
  payableAmount: null,
  payableDays: null,
  payableId: '',
  policyNo: '',
  productCode: '',
  remainingDays: null,
  remark: '',
  saPercentage: null,
  saPercentagePerWeek: null,
  systemCalculationAmount: null,
  transId: '',
  treatmentId: '',
  treatmentPayableId: '',
  payableYears: 1,
  saPercentagePerYear: null,
  remainingYears: null,
};

const INCIDENTDECISIONITEM = {
  benefitTypeCode: '',
  claimNo: '',
  creator: '',
  decision: 'A',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  modifier: '',
  policyId: '',
  productCode: '',
  remark: '',
  transId: '',
};

const DATEOFTREATMENTITEM = {
  claimNo: '',
  creator: '',
  deleted: 0,
  gmtCreate: '',
  gmtModified: '',
  id: '',
  medicineId: '',
  modifier: '',
  transId: '',
  treatmentDate: null,
  treatmentId: '',
};

const EXPECTDECISION = {
  assessObject: '',
  assessObjectId: '',
  assessorOverrideAmount: null,
  assessorOverrideDays: null,
  assessorOverrideDeductible: null,
  assessorOverrideMultiple: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  claimDecision: '',
  claimNo: '',
  decisionId: '',
  incidentBenefitId: '',
  incidentId: '',
  operation: '',
  policyCategory: '',
  policyId: '',
  policySetupStatus: '',
  productCode: '',
  treatmentId: '',
};

const EXPECTPOLICYCLAIM = {
  claimNo: '',
  parentClaimNo: '',
  policyId: '',
  incidentId: '',
  operation: 'E',
  splitLevel: 'claim',
};

const EXPECTPOLICYINCIDENT = {
  parentClaimNo: '',
  applicationNo: '',
  claimNo: '',
  policyId: '',
  incidentIds: '',
  operation: 'E',
  splitLevel: 'incident',
};

export {
  INCIDENTITEM,
  JPINCIDENTITEM,
  DIAGNOSISITEM,
  TREATMENTITEM,
  MAINBENEFITITEM,
  PROCEDUREITEM,
  OTHERPROCEDUREITEM,
  INVOICEITEM,
  SERVICEITEM,
  POLICYBENEFITITEM,
  BENEFICIARYITEM,
  PAYEEITEM,
  CLAIMPAYABLEITEM,
  LIFEPAYABLE,
  TREATMENTPAYABLEITEM,
  INVOICEPAYABLEITEM,
  SERVICEPAYABLEITEM,
  JPMEDICINETREATMENT,
  JPTREATMENTDATE,
  BENEFITITEMPAYABLEITEM,
  INCIDENTDECISIONITEM,
  PAYEEINFO,
  ACCIDENT_BENEFIT_PAYABLE_ITEM,
  DATEOFTREATMENTITEM,
  EXPECTDECISION,
  EXPECTPOLICYCLAIM,
  EXPECTPOLICYINCIDENT,
};
