enum Case {
  'Case No' = 'processInstanceId',
  'Claim No' = 'inquiryBusinessNo',
  'Case Category' = 'caseCategory',
  'Submission Date' = 'submissionDate',
  'Business Decision' = 'businessDecision',
  'Creation Date' = 'creationDate',
  'Due Date' = 'dueDate',
  'Remaining Time' = 'remainingTime',
  'Client Name' = 'clientName',
  'Current Activity' = 'currentActivity',
  'Batch No' = 'batchNo',
  'Policy No' = 'policyNo',
  'ID/Passport No' = 'identityNo',
  'Business Type' = 'businessType',
  'Submission Channel' = 'submissionChannel',
  'Entity' = 'companyCode',
  'Policy Owner Name' = 'policyOwnerName',
  'Insured Name' = 'insuredName',
  'Case Label' = 'labelCodeList',
}

enum user {
  'User ID' = 'userId',
  'User Name' = 'userName',
  'Status' = 'status',
  'Organization' = 'organizationCode',
  'Employment Date' = 'employmentDate',
  'Title' = 'title',
  'Report To' = 'directSupervisor',
}
enum task {
  'Submission Date' = 'submissionDate',
  'Case No' = 'processInstanceId',
  'Claim No' = 'inquiryBusinessNo',
  'Case Category' = 'caseCategory',
  'Activity' = 'activityKey',
  'Business Type' = 'businessType',
  'Status' = 'taskStatus',
  'Assignee' = 'assignee',
  'Batch No' = 'batchNo',
  'Due Date' = 'dueDate',
  'Remaining Time' = 'remainingTime',
  'Client Name' = 'clientName',
  'Policy No' = 'policyNo',
  'Date Of Eligibility Check' = 'eligibilityCheckDate',
  'Arrival Date' = 'firstFormReceiveDate',
  'Creation Date' = 'startTime',
  'Completed Date' = 'endTime',
  'Active Pending Item' = 'pendingReason',
  'Reminder Send Date' = 'reminderTime',
  'ID/Passport No' = 'identityNo',
  'Submission Channel' = 'submissionChannel',
  'Entity' = 'companyCode',
  'Case Label' = 'labelCodeList',
}
enum claimhistory {
  'Claim No' = 'inquiryClaimNo',
  'Case No' = 'caseNo',
  'Case Category' = 'caseCategory',
  'Insured Name' = 'insuredName',
  'Claim Type' = 'claimType',
  'Assessment Decision' = 'assessmentDecision',
  'Payment Amount' = 'paymentAmount',
  'Submission Date' = 'submissionDate',
  'Close Date' = 'closeDate',
  'Policy No' = 'policyNo',
  'labelId/Passport No' = 'identityNo',
  'Client labelId' = 'clientId',
  'Final Status' = 'finalStatus',
  'Contract Type' = 'contractType',
  'Entity' = 'companyCode',
  'Insured ID No.' = 'identityNo',
  'External Settled Date' = 'externalSettledDate',
}
enum hospitalbilling {
  'Hospital Name' = 'hospitalName',
  'Status' = 'status',
  'Scan Date' = 'scanDate',
}
enum document {
  'Document ID' = 'docId',
  'Document Type' = 'docTypeCode',
  'Document Classification' = 'classification',
  'Submission Batch No.' = 'batchNo',
  'Case No.' = 'caseNo',
  'Claim No.' = 'parentBusinessNo',
  'Insured Name' = 'insuredName',
  'Policy No.' = 'policyId',
}
enum rule {
  'Rule Set Name' = 'ruleSetName',
  'Rule Set Id' = 'ruleSetId',
  'Module' = 'moduleCode',
  'Rule Set Type' = 'ruleSetType',
  'Effective Date' = 'effectiveDate',
  'Expired Date' = 'expiredDate',
  'Expected Publish Date' = 'expectedPublishDate',
  'Actual Publish Time' = 'actualPublishTime',
}
enum nbhistoryinquiry {
  'Policy No.' = 'policyNo',
  'Business No.' = 'businessNo',
  'Policy Owner' = 'policyOwner',
  'Policy Owner ID' = 'policyOwnerId',
  'Insured Name' = 'insuredName',
  'Submission Channel' = 'submissionChannel',
  'Submission Date' = 'submissionDate',
  'UW Decision' = 'UWDecision',
  'Final Status' = 'finalStatus',
}
enum servicinghistory {
  'BusinessNo' = 'inquiryBusinessNo',
  'policyNo' = 'policyNo',
  'policyOwner' = 'policyOwner',
  'insuredName' = 'insuredName',
  'transactionType' = 'businessTypeCode',
  'submissionDate' = 'submissionDate',
  'submissionChannel' = 'submissionChannel',
  'finalStatus' = 'finalStatus',
}

export default {
  case: Case,
  user,
  task,
  claimhistory,
  hospitalbilling,
  document,
  rule,
  nbhistoryinquiry,
  servicinghistory,
};
