import BasicInfoDisplayMode from 'process/NB/ManualUnderwriting/Enum/BasicInfoDisplayMode';
import GenerateSIStatus from 'process/NB/ManualUnderwriting/Enum/GenerateSIStatus';

export default {
  clientDetailList: [],
  selectedClient: '',
  expendedClient: '',
  allReasonConfigList: [],
  addressSubList: [],
  allAddressSubList: [],
  isShowPopUpDecision: false,
  isShowNtuModal: false,
  businessData: {},
  businessDataValue: {},
  initialBusinessData: {},
  activeProductCode: [],
  productSection: {},
  policySection: {},
  benefitSection: {},
  nbHistoryData: {},
  currencySection: {
    currency: 'SGD',
  },
  ntuDataObject: {},
  addPopExclusionList: [],
  productNameList: [
    {
      dictCode: 'All',
      dictName: 'All',
      index: 0,
    },
  ],
  clientNameDicts: [],
  policyLevelDecisionList: [
    {
      typeCode: 'Dropdown_COM_UWDecision',
      dictCode: 'A',
      dictName: 'Approve',
    },
    {
      typeCode: 'Dropdown_COM_UWDecision',
      dictCode: 'P',
      dictName: 'Postpone',
    },
    {
      typeCode: 'Dropdown_COM_UWDecision',
      dictCode: 'D',
      dictName: 'Decline',
    },
  ],
  exclusionList: [],
  isShowBtn: true,
  totalError: false,
  currencyEditable: false,
  clientNameList: [],
  stepsChange: {
    ClientInfo: false,
    PlanInfo: false,
    OtherInfo: false,
  },
  uwProposalAgent: {},
  isAddProductExclusion: false,
  indentificationModalVisible: false,
  originBizData: {},
  taskDetail: {},
  coverageClientList: [],
  clientsQuestionnaire: [],
  ewsData: [],
  caseDetail: {},
  currencyCode: '',
  exchangeRate: {},
  clientsData: {},
  address: {
    country: [],
    province: {},
    city: {},
    district: {},
    commune: {},
    village: {},
    street: {},
  },
  planProductConfig: {
    requiredProductCodeList: [],
    basicPlanProductFeatureList: [],
    otherPlanProductFeatureList: [],
  },
  bankCodeList: [],
  branchCodeList: [],
  bankChannelList: [],
  factoringHousesList: [],
  defaultCurrentAddressType: 'C',
  questionnaireSwitch: false,
  diffSource: {},
  addLoadingModalVisible: false,
  addingLoadingItems: [],
  addingLoadingSelectedProduct: {},
  agentData: [],
  UWMeLinkAge: '',
  linkDicts: {},
  ageChange: false,
  relationOfProposerDefaultvalue: '',
  numberofunitsList: [],
  basicInfoDisplayMode: BasicInfoDisplayMode.Editing,
  underwritingApproach: '',
  cfgPlanProductOptions: [],
  contractType: [],
  generateSIStatus: GenerateSIStatus.Init,
  checkRule: '',
  cfgRegionalDefaultValueList: [],
  specificCfgFactoringHouseList: [],
  adultAge: null,
  paymentListData: {},
  overdueTime: '',
  planLoadingReasons: [],
  listDedupCheckCfg: [],
  checkDuplicating: '',
  addDPRemarkModalVisible: false,
  addDPRemarkSelectedProduct: {},
  addDPRemarkItems: [],
  cfgPlanHospitalBenefits: [],
  sustainabilityCaseModal: false,
  sustainabilityCheckingData: {},
  sustainabilityCheckingSelected: '',
  possibleSusOptNames: [],
  possibleSusOptNamesSelected: [],
  isShowRuleResultsModal: false,
  ruleResultList: [],
  loadingAllowableConfigs: [],
  loadingMappingRule: [],
  riskIndicatorConfigList: [],
  updatePolicyModalVisible: false,
  updatingPolicyOriginalDraft: {},
  waiveLoadingModalVisible: false,
  ropListMap: {},
  idDisplayConfigList: [],
  fecRiskMsg: '',
  ewsDataMap: {},
  currentVersionEWS: {},
  productCodeConfig: {},
  exclusionReasonList: [],
  showPaymentTransferModal: false,
  transferAddItem: {},
  cascadeAdress: {},
  proposalLoading: false,
  occupationFullList: {},
  distributionChannelDisplayMethod: null,
};
