export default (state: any) => ({
  visible: false,
  selectClient: '',
  selectQuestionnaire: '',
  roleByClientMap: {},
  sectionMap: {},
  customerQuestionnaireList: [],
  error: {},
  validating: false,
  processData: [],
  entities: {},
  otherPayload: {},
  isNB: true,
  isAgentName: true,
});
