// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from '/Users/226838/Documents/company/owb/Venus-UI/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
