// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/atomConfig/atomConfig';
import model_2 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/auditLog/auditLogConroller';
import model_3 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/auth/authController';
import model_4 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/batchProcess';
import model_5 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/bizProcess';
import model_6 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/commonCaseCreate';
import model_7 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/contactsAssigneeList';
import model_8 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/envoyController';
import model_9 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/informationController';
import model_10 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/process';
import model_11 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpm/processTask';
import model_12 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpsrv/BPSRVOfDataCaptureController';
import model_13 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/bpsrv/BPSRVOfServicingDecisionController';
import model_14 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/checkRBAC';
import model_15 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/apOfClaimAssessmentController';
import model_16 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/apOfClaimCaseController';
import model_17 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/AppealCase/MaAppealCaseController';
import model_18 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/AppealCaseController';
import model_19 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/calculationPath';
import model_20 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/caseSplitCaseController';
import model_21 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/caseSplitController';
import model_22 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/caseSplitDocumentController';
import model_23 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/caseSplitIncidentController';
import model_24 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/caseSplitPolicyController';
import model_25 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/claimCaseController';
import model_26 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/claimDataStatus';
import model_27 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/commonClaimAssessmentController';
import model_28 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/daOfClaimAssessmentController';
import model_29 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/daOfClaimCaseController';
import model_30 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/daProcessController';
import model_31 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/exceptionalHandlingController';
import model_32 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/hbOfClaimAssessmentController';
import model_33 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/hbProcessController';
import model_34 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/HongKong/HKCLMOfClaimAssessmentController';
import model_35 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/HongKong/HKCLMOfDataCaptureController';
import model_36 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/HongKong/HKCLMOfPMAChequeController';
import model_37 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/HongKong/hkProcessController';
import model_38 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Indonesia/IDCLMOfClaimAssessmentController';
import model_39 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Indonesia/IDCLMOfDataCaptureController';
import model_40 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Indonesia/idProcessController';
import model_41 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/insured360';
import model_42 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLM/JPCLMOfClaimAssessmentController';
import model_43 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLM/JPCLMOfClaimRegistrationController';
import model_44 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLM/JPCLMOfQualityControl';
import model_45 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLM/JPCLMProcessController';
import model_46 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLMOfClaimAssessment';
import model_47 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLMOfDataCapture';
import model_48 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Japan/JPCLMProcessCreate';
import model_49 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/JPDPOfDocumentDispatchController';
import model_50 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/medicalSearch';
import model_51 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/medicalValidate';
import model_52 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/MenuCreateCase/claimNo';
import model_53 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/mjProcessController';
import model_54 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/paymentAllocation';
import model_55 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/MYCLMOfClaimPaymentTrackController';
import model_56 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/MYCLMOfCTG008AssessmentController';
import model_57 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/MYCLMOfCTG008DataCaptureController';
import model_58 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/PHCLMOfAppealCaseController';
import model_59 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/PHCLMOfClaimAssessmentController';
import model_60 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/PHCLMOfClaimPaymentTrackController';
import model_61 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/PHCLMOfCTG008AssessmentController';
import model_62 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/PHCLMOfCTG008DataCaptureController';
import model_63 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Philippines/PHCLMOfDataCaptureController';
import model_64 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/requestWarnMessageController';
import model_65 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/sequence';
import model_66 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand/followUpClaim';
import model_67 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand/IdentifyHospitalBatchController';
import model_68 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand/UnknownDocument/UDOfCreateController';
import model_69 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand/UnknownDocument/UnknownDocumentController';
import model_70 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand2/THCLMOfClaimAssessmentController';
import model_71 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand2/THCLMOfDataCaptureController';
import model_72 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/Thailand2/thProcessController';
import model_73 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/udMessageController';
import model_74 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claim/UserPermission/permissionMaintenanceController';
import model_75 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claimBasicProduct/bpOfClaimAssessmentController';
import model_76 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claimBasicProduct/bpOfDataCaptureController';
import model_77 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claimBasicProduct/bpProcessController';
import model_78 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claimBasicProduct/simplifiedDigitalController';
import model_79 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/claimBasicProduct/UnknownDocumentBaseController';
import model_80 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/common/claimEditable';
import model_81 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/common/listener';
import model_82 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configController';
import model_83 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationCenter';
import model_84 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationDataField';
import model_85 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationDataimage';
import model_86 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationExcel';
import model_87 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationMenu';
import model_88 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationOperation';
import model_89 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationRegistration';
import model_90 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationSetup';
import model_91 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationCenter/configurationTabs';
import model_92 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationProcess/ConfigureRole/configureRoleController';
import model_93 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationProcess/ConfigureUser/configureUserController';
import model_94 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationProcess/DataMainTenanceForBusiness/dataConfigurationController';
import model_95 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/ConfigurationProcess/DataMainTenanceForBusiness/permissionConfigurationController';
import model_96 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configuration/NavigatorConfiguration/configurationController';
import model_97 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/configureUserGroupController';
import model_98 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/dictionaryController';
import model_99 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/document/batchDocumentScanningController';
import model_100 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/document/documentManagement';
import model_101 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/document/DocumentOfDelete';
import model_102 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/document/documentScanningController';
import model_103 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/document/OcrResults';
import model_104 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/document/policyDocument';
import model_105 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/flowUp';
import model_106 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/formCommonController';
import model_107 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/generalPOS/GeneralPOSAgentQuestionnaireController';
import model_108 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/generalPOS/generalPOSController';
import model_109 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/generalPOS/GeneralPOSRoleQuestionnaireController';
import model_110 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/generalPOS/PHBatchCreateProcessController';
import model_111 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/generalPOS/PHNotCFTController';
import model_112 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/global';
import model_113 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/integration/integration';
import model_114 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/leaveManagement/leaveManagement';
import model_115 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/login';
import model_116 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/manuallyWorkflow/manuallyWorkflowController';
import model_117 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/medicalRequestFlow';
import model_118 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/advancedQueryAllForm';
import model_119 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/advancedQueryBatchAssign';
import model_120 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/advancedQueryController';
import model_121 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/advancedQueryOfCase';
import model_122 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/advancedQueryOfHospitalBiling';
import model_123 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/advancedQueryUserCardController';
import model_124 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/chatController';
import model_125 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/converseController';
import model_126 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/customization';
import model_127 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/dashboard';
import model_128 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/dashboardController';
import model_129 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/flowDetailError';
import model_130 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/homeList';
import model_131 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/homeModeBtn';
import model_132 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/homeTaskFlow';
import model_133 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/homeTaskFlowFilter';
import model_134 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/homeWatching';
import model_135 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/hospitalDetailController';
import model_136 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/hotkey';
import model_137 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/hotkeyGlobal';
import model_138 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/language';
import model_139 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/mode';
import model_140 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/NewAdvancedQueryController';
import model_141 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/notificationController';
import model_142 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/overdueList';
import model_143 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/reportCenterController';
import model_144 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/reportCenterOldController';
import model_145 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/smartCircleNotification';
import model_146 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/task';
import model_147 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/taskFolder';
import model_148 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/userContactController';
import model_149 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/userGeneralInfoController';
import model_150 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/userManagement';
import model_151 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceAI';
import model_152 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceCases';
import model_153 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceHistory';
import model_154 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceNBHistory';
import model_155 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceServicingHistory';
import model_156 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceSwitchOn';
import model_157 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/navigator/workspaceUser';
import model_158 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/nb/agentQuestionnaireController';
import model_159 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/nb/customerIdentification';
import model_160 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/nb/FECApprovalController';
import model_161 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/nb/manualUnderwriting';
import model_162 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/nb/premiumSettlement';
import model_163 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/nb/UWWSQuestionnaire';
import model_164 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/newBusiness/ews';
import model_165 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/newBusiness/manualUnderwriting';
import model_166 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/originalSubmissionDataView/originalSubmissionDataView';
import model_167 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/paEngine/vnbCalculator';
import model_168 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/phowb/batchCreateProcess';
import model_169 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/phowb/phowbDataCaptureController';
import model_170 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/processInstance';
import model_171 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/questionnaireController';
import model_172 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/ruleEngine/ruleEngineController';
import model_173 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/selectOptionsDictionary';
import model_174 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/serviceSystemControllerService';
import model_175 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/siderWorkSpace';
import model_176 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/solutionRead';
import model_177 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/sqlController';
import model_178 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/supportCenter/supportCenterController';
import model_179 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/tarckPoint/tarckPointController';
import model_180 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/theme';
import model_181 from '/Users/226838/Documents/company/owb/Venus-UI/src/models/user';

export const models = {
model_1: { namespace: 'atomConfig.atomConfig', model: model_1 },
model_2: { namespace: 'auditLog.auditLogConroller', model: model_2 },
model_3: { namespace: 'auth.authController', model: model_3 },
model_4: { namespace: 'bpm.batchProcess', model: model_4 },
model_5: { namespace: 'bpm.bizProcess', model: model_5 },
model_6: { namespace: 'bpm.commonCaseCreate', model: model_6 },
model_7: { namespace: 'bpm.contactsAssigneeList', model: model_7 },
model_8: { namespace: 'bpm.envoyController', model: model_8 },
model_9: { namespace: 'bpm.informationController', model: model_9 },
model_10: { namespace: 'bpm.process', model: model_10 },
model_11: { namespace: 'bpm.processTask', model: model_11 },
model_12: { namespace: 'bpsrv.BPSRVOfDataCaptureController', model: model_12 },
model_13: { namespace: 'bpsrv.BPSRVOfServicingDecisionController', model: model_13 },
model_14: { namespace: 'checkRBAC', model: model_14 },
model_15: { namespace: 'claim.apOfClaimAssessmentController', model: model_15 },
model_16: { namespace: 'claim.apOfClaimCaseController', model: model_16 },
model_17: { namespace: 'claim.AppealCase.MaAppealCaseController', model: model_17 },
model_18: { namespace: 'claim.AppealCaseController', model: model_18 },
model_19: { namespace: 'claim.calculationPath', model: model_19 },
model_20: { namespace: 'claim.caseSplitCaseController', model: model_20 },
model_21: { namespace: 'claim.caseSplitController', model: model_21 },
model_22: { namespace: 'claim.caseSplitDocumentController', model: model_22 },
model_23: { namespace: 'claim.caseSplitIncidentController', model: model_23 },
model_24: { namespace: 'claim.caseSplitPolicyController', model: model_24 },
model_25: { namespace: 'claim.claimCaseController', model: model_25 },
model_26: { namespace: 'claim.claimDataStatus', model: model_26 },
model_27: { namespace: 'claim.commonClaimAssessmentController', model: model_27 },
model_28: { namespace: 'claim.daOfClaimAssessmentController', model: model_28 },
model_29: { namespace: 'claim.daOfClaimCaseController', model: model_29 },
model_30: { namespace: 'claim.daProcessController', model: model_30 },
model_31: { namespace: 'claim.exceptionalHandlingController', model: model_31 },
model_32: { namespace: 'claim.hbOfClaimAssessmentController', model: model_32 },
model_33: { namespace: 'claim.hbProcessController', model: model_33 },
model_34: { namespace: 'claim.HongKong.HKCLMOfClaimAssessmentController', model: model_34 },
model_35: { namespace: 'claim.HongKong.HKCLMOfDataCaptureController', model: model_35 },
model_36: { namespace: 'claim.HongKong.HKCLMOfPMAChequeController', model: model_36 },
model_37: { namespace: 'claim.HongKong.hkProcessController', model: model_37 },
model_38: { namespace: 'claim.Indonesia.IDCLMOfClaimAssessmentController', model: model_38 },
model_39: { namespace: 'claim.Indonesia.IDCLMOfDataCaptureController', model: model_39 },
model_40: { namespace: 'claim.Indonesia.idProcessController', model: model_40 },
model_41: { namespace: 'claim.insured360', model: model_41 },
model_42: { namespace: 'claim.Japan.JPCLM.JPCLMOfClaimAssessmentController', model: model_42 },
model_43: { namespace: 'claim.Japan.JPCLM.JPCLMOfClaimRegistrationController', model: model_43 },
model_44: { namespace: 'claim.Japan.JPCLM.JPCLMOfQualityControl', model: model_44 },
model_45: { namespace: 'claim.Japan.JPCLM.JPCLMProcessController', model: model_45 },
model_46: { namespace: 'claim.Japan.JPCLMOfClaimAssessment', model: model_46 },
model_47: { namespace: 'claim.Japan.JPCLMOfDataCapture', model: model_47 },
model_48: { namespace: 'claim.Japan.JPCLMProcessCreate', model: model_48 },
model_49: { namespace: 'claim.JPDPOfDocumentDispatchController', model: model_49 },
model_50: { namespace: 'claim.medicalSearch', model: model_50 },
model_51: { namespace: 'claim.medicalValidate', model: model_51 },
model_52: { namespace: 'claim.MenuCreateCase.claimNo', model: model_52 },
model_53: { namespace: 'claim.mjProcessController', model: model_53 },
model_54: { namespace: 'claim.paymentAllocation', model: model_54 },
model_55: { namespace: 'claim.Philippines.MYCLMOfClaimPaymentTrackController', model: model_55 },
model_56: { namespace: 'claim.Philippines.MYCLMOfCTG008AssessmentController', model: model_56 },
model_57: { namespace: 'claim.Philippines.MYCLMOfCTG008DataCaptureController', model: model_57 },
model_58: { namespace: 'claim.Philippines.PHCLMOfAppealCaseController', model: model_58 },
model_59: { namespace: 'claim.Philippines.PHCLMOfClaimAssessmentController', model: model_59 },
model_60: { namespace: 'claim.Philippines.PHCLMOfClaimPaymentTrackController', model: model_60 },
model_61: { namespace: 'claim.Philippines.PHCLMOfCTG008AssessmentController', model: model_61 },
model_62: { namespace: 'claim.Philippines.PHCLMOfCTG008DataCaptureController', model: model_62 },
model_63: { namespace: 'claim.Philippines.PHCLMOfDataCaptureController', model: model_63 },
model_64: { namespace: 'claim.requestWarnMessageController', model: model_64 },
model_65: { namespace: 'claim.sequence', model: model_65 },
model_66: { namespace: 'claim.Thailand.followUpClaim', model: model_66 },
model_67: { namespace: 'claim.Thailand.IdentifyHospitalBatchController', model: model_67 },
model_68: { namespace: 'claim.Thailand.UnknownDocument.UDOfCreateController', model: model_68 },
model_69: { namespace: 'claim.Thailand.UnknownDocument.UnknownDocumentController', model: model_69 },
model_70: { namespace: 'claim.Thailand2.THCLMOfClaimAssessmentController', model: model_70 },
model_71: { namespace: 'claim.Thailand2.THCLMOfDataCaptureController', model: model_71 },
model_72: { namespace: 'claim.Thailand2.thProcessController', model: model_72 },
model_73: { namespace: 'claim.udMessageController', model: model_73 },
model_74: { namespace: 'claim.UserPermission.permissionMaintenanceController', model: model_74 },
model_75: { namespace: 'claimBasicProduct.bpOfClaimAssessmentController', model: model_75 },
model_76: { namespace: 'claimBasicProduct.bpOfDataCaptureController', model: model_76 },
model_77: { namespace: 'claimBasicProduct.bpProcessController', model: model_77 },
model_78: { namespace: 'claimBasicProduct.simplifiedDigitalController', model: model_78 },
model_79: { namespace: 'claimBasicProduct.UnknownDocumentBaseController', model: model_79 },
model_80: { namespace: 'common.claimEditable', model: model_80 },
model_81: { namespace: 'common.listener', model: model_81 },
model_82: { namespace: 'configController', model: model_82 },
model_83: { namespace: 'configuration.ConfigurationCenter.configurationCenter', model: model_83 },
model_84: { namespace: 'configuration.ConfigurationCenter.configurationDataField', model: model_84 },
model_85: { namespace: 'configuration.ConfigurationCenter.configurationDataimage', model: model_85 },
model_86: { namespace: 'configuration.ConfigurationCenter.configurationExcel', model: model_86 },
model_87: { namespace: 'configuration.ConfigurationCenter.configurationMenu', model: model_87 },
model_88: { namespace: 'configuration.ConfigurationCenter.configurationOperation', model: model_88 },
model_89: { namespace: 'configuration.ConfigurationCenter.configurationRegistration', model: model_89 },
model_90: { namespace: 'configuration.ConfigurationCenter.configurationSetup', model: model_90 },
model_91: { namespace: 'configuration.ConfigurationCenter.configurationTabs', model: model_91 },
model_92: { namespace: 'configuration.ConfigurationProcess.ConfigureRole.configureRoleController', model: model_92 },
model_93: { namespace: 'configuration.ConfigurationProcess.ConfigureUser.configureUserController', model: model_93 },
model_94: { namespace: 'configuration.ConfigurationProcess.DataMainTenanceForBusiness.dataConfigurationController', model: model_94 },
model_95: { namespace: 'configuration.ConfigurationProcess.DataMainTenanceForBusiness.permissionConfigurationController', model: model_95 },
model_96: { namespace: 'configuration.NavigatorConfiguration.configurationController', model: model_96 },
model_97: { namespace: 'configureUserGroupController', model: model_97 },
model_98: { namespace: 'dictionaryController', model: model_98 },
model_99: { namespace: 'document.batchDocumentScanningController', model: model_99 },
model_100: { namespace: 'document.documentManagement', model: model_100 },
model_101: { namespace: 'document.DocumentOfDelete', model: model_101 },
model_102: { namespace: 'document.documentScanningController', model: model_102 },
model_103: { namespace: 'document.OcrResults', model: model_103 },
model_104: { namespace: 'document.policyDocument', model: model_104 },
model_105: { namespace: 'flowUp', model: model_105 },
model_106: { namespace: 'formCommonController', model: model_106 },
model_107: { namespace: 'generalPOS.GeneralPOSAgentQuestionnaireController', model: model_107 },
model_108: { namespace: 'generalPOS.generalPOSController', model: model_108 },
model_109: { namespace: 'generalPOS.GeneralPOSRoleQuestionnaireController', model: model_109 },
model_110: { namespace: 'generalPOS.PHBatchCreateProcessController', model: model_110 },
model_111: { namespace: 'generalPOS.PHNotCFTController', model: model_111 },
model_112: { namespace: 'global', model: model_112 },
model_113: { namespace: 'integration.integration', model: model_113 },
model_114: { namespace: 'leaveManagement.leaveManagement', model: model_114 },
model_115: { namespace: 'login', model: model_115 },
model_116: { namespace: 'manuallyWorkflow.manuallyWorkflowController', model: model_116 },
model_117: { namespace: 'medicalRequestFlow', model: model_117 },
model_118: { namespace: 'navigator.advancedQueryAllForm', model: model_118 },
model_119: { namespace: 'navigator.advancedQueryBatchAssign', model: model_119 },
model_120: { namespace: 'navigator.advancedQueryController', model: model_120 },
model_121: { namespace: 'navigator.advancedQueryOfCase', model: model_121 },
model_122: { namespace: 'navigator.advancedQueryOfHospitalBiling', model: model_122 },
model_123: { namespace: 'navigator.advancedQueryUserCardController', model: model_123 },
model_124: { namespace: 'navigator.chatController', model: model_124 },
model_125: { namespace: 'navigator.converseController', model: model_125 },
model_126: { namespace: 'navigator.customization', model: model_126 },
model_127: { namespace: 'navigator.dashboard', model: model_127 },
model_128: { namespace: 'navigator.dashboardController', model: model_128 },
model_129: { namespace: 'navigator.flowDetailError', model: model_129 },
model_130: { namespace: 'navigator.homeList', model: model_130 },
model_131: { namespace: 'navigator.homeModeBtn', model: model_131 },
model_132: { namespace: 'navigator.homeTaskFlow', model: model_132 },
model_133: { namespace: 'navigator.homeTaskFlowFilter', model: model_133 },
model_134: { namespace: 'navigator.homeWatching', model: model_134 },
model_135: { namespace: 'navigator.hospitalDetailController', model: model_135 },
model_136: { namespace: 'navigator.hotkey', model: model_136 },
model_137: { namespace: 'navigator.hotkeyGlobal', model: model_137 },
model_138: { namespace: 'navigator.language', model: model_138 },
model_139: { namespace: 'navigator.mode', model: model_139 },
model_140: { namespace: 'navigator.NewAdvancedQueryController', model: model_140 },
model_141: { namespace: 'navigator.notificationController', model: model_141 },
model_142: { namespace: 'navigator.overdueList', model: model_142 },
model_143: { namespace: 'navigator.reportCenterController', model: model_143 },
model_144: { namespace: 'navigator.reportCenterOldController', model: model_144 },
model_145: { namespace: 'navigator.smartCircleNotification', model: model_145 },
model_146: { namespace: 'navigator.task', model: model_146 },
model_147: { namespace: 'navigator.taskFolder', model: model_147 },
model_148: { namespace: 'navigator.userContactController', model: model_148 },
model_149: { namespace: 'navigator.userGeneralInfoController', model: model_149 },
model_150: { namespace: 'navigator.userManagement', model: model_150 },
model_151: { namespace: 'navigator.workspaceAI', model: model_151 },
model_152: { namespace: 'navigator.workspaceCases', model: model_152 },
model_153: { namespace: 'navigator.workspaceHistory', model: model_153 },
model_154: { namespace: 'navigator.workspaceNBHistory', model: model_154 },
model_155: { namespace: 'navigator.workspaceServicingHistory', model: model_155 },
model_156: { namespace: 'navigator.workspaceSwitchOn', model: model_156 },
model_157: { namespace: 'navigator.workspaceUser', model: model_157 },
model_158: { namespace: 'nb.agentQuestionnaireController', model: model_158 },
model_159: { namespace: 'nb.customerIdentification', model: model_159 },
model_160: { namespace: 'nb.FECApprovalController', model: model_160 },
model_161: { namespace: 'nb.manualUnderwriting', model: model_161 },
model_162: { namespace: 'nb.premiumSettlement', model: model_162 },
model_163: { namespace: 'nb.UWWSQuestionnaire', model: model_163 },
model_164: { namespace: 'newBusiness.ews', model: model_164 },
model_165: { namespace: 'newBusiness.manualUnderwriting', model: model_165 },
model_166: { namespace: 'originalSubmissionDataView.originalSubmissionDataView', model: model_166 },
model_167: { namespace: 'paEngine.vnbCalculator', model: model_167 },
model_168: { namespace: 'phowb.batchCreateProcess', model: model_168 },
model_169: { namespace: 'phowb.phowbDataCaptureController', model: model_169 },
model_170: { namespace: 'processInstance', model: model_170 },
model_171: { namespace: 'questionnaireController', model: model_171 },
model_172: { namespace: 'ruleEngine.ruleEngineController', model: model_172 },
model_173: { namespace: 'selectOptionsDictionary', model: model_173 },
model_174: { namespace: 'serviceSystemControllerService', model: model_174 },
model_175: { namespace: 'siderWorkSpace', model: model_175 },
model_176: { namespace: 'solutionRead', model: model_176 },
model_177: { namespace: 'sqlController', model: model_177 },
model_178: { namespace: 'supportCenter.supportCenterController', model: model_178 },
model_179: { namespace: 'tarckPoint.tarckPointController', model: model_179 },
model_180: { namespace: 'theme', model: model_180 },
model_181: { namespace: 'user', model: model_181 },
} as const
