import judgeDisplaySustainabiliy from 'process/NB/ManualUnderwriting/utils/judgeDisplaySustainabiliy';

describe('judgeDisplaySustainabiliy', () => {
  test('some sustainable is Y', () => {
    const businessData = {
      sustainabilityOptions: [
        {
          creator: null,
          gmtModified: null,
          sustainable: 'Y',
          applied: null,
          transId: null,
          applicationNo: 'JZSC031501',
          modifier: null,
          remark: '[]',
          gmtCreate: null,
          version: 129,
          deleted: 0,
          round: 1,
          policyId: 'AL010472',
          selectedOptions: [
            {
              rtCoverage: {
                discountRate: null,
                discount: 0,
                planName: null,
                planCategory: null,
                coverageNo: null,
                initialPrem: 1840,
                productName: null,
                embedIndicator: null,
                occupationLoading: null,
                occupationType: null,
                coverageExclusionList: null,
                calculateBy: null,
                loadingPremium: 0,
                id: 'd81fda54-96b3-40ba-86c0-616c4b8bb2ed',
                embedFlag: null,
                underwritingType: null,
                priority: null,
                coreCode: 'RT07',
                unionInsuredSeqNum: null,
                saWaiver: null,
                rspPremiumTerm: null,
                grossPremium: 1840,
                premiumTermType: null,
                annualizedPrem: 7360,
                gmtModified: null,
                finalCoi: null,
                componentDescriptionLocal: null,
                premiumMode: null,
                loadedPremium: 1840,
                timeRiskMark: null,
                laPremium: 1840,
                rsp: null,
                indemnifyPeriodUnit: 'Y',
                sumAssured: null,
                jointLifeNo: '00',
                indemnifyPeriod: '5',
                riskType: null,
                laCategory: null,
                customerSegment: null,
                componentDescriptionEn: null,
                benefitSubType: null,
                creator: null,
                extraCoi: null,
                coverageBenefitsList: null,
                packageId: null,
                coverageRemarkList: null,
                gmtCreate: null,
                subProductType: null,
                deleted: 0,
                productCode: null,
                numberOfUnits: null,
                annualLimit: null,
                policyId: 'AL010472',
                basePremium: 1840,
                stampDuty: null,
                loadingRule: null,
                rspCharge: null,
                packageCode: null,
                backDay: null,
                instalmentPremiumWithTax: 1840,
                matureDate: null,
                annualPrem: 7360,
                currencyCode: 'MYR',
                upToAge: null,
                notManualRemove: null,
                transId: null,
                applicationNo: 'JZSC031501',
                modifier: null,
                pid: 'RTIL',
                systemAutoAddInd: null,
                pbCodes: null,
                productLine: null,
                isBack: null,
                compareSeq: null,
                isExemptions: null,
                monthlyPrem: 613.33,
                waiveProductList: null,
                lifeNo: '01',
                isMain: 'N',
                tax: null,
                hospitalPlanCode: null,
                payerIndicator: null,
                unit: null,
                loanInfoList: null,
                taxAmount: 0,
                coverageDecision: null,
                sustainabilityChecking: null,
                riderNo: null,
                sinceCertificateYear: 1,
                coverageFundInfoList: [
                  {
                    totalFundAllocation: '100',
                    coverageId: '2fdd0f0e-f476-457c-a3a5-768b75bea1f0',
                    autoRebalancingStatus: null,
                    creator: 'MYSLLO',
                    gmtModified: '2023-03-27T10:41:32.266+0000',
                    transId: '4ee17e69-588a-4e29-bc24-18dd9f651586',
                    applicationNo: 'JZSC031501',
                    modifier: '0',
                    autoRebalancingType: null,
                    ownFundInfoList: [
                      {
                        coverageId: '2fdd0f0e-f476-457c-a3a5-768b75bea1f0',
                        creator: 'MYSLLO',
                        gmtModified: '2023-03-27T10:41:32.269+0000',
                        fundInfoId: 'aa24e7d6-e9d2-4812-a4de-db9f7fab7c68',
                        transId: '4ee17e69-588a-4e29-bc24-18dd9f651586',
                        applicationNo: 'JZSC031501',
                        modifier: '0',
                        fundMeasure: 'P',
                        fundCurrency: 'MYR',
                        gmtCreate: '2023-03-27T10:41:32.269+0000',
                        deleted: 0,
                        fundCode: 'APEA',
                        sortOrder: 1,
                        fundAllocation: '50',
                        allocationAccount: null,
                        id: 'c370f5ca-8857-4816-bf9c-a9398104c140',
                        fundName: null,
                      },
                      {
                        coverageId: '2fdd0f0e-f476-457c-a3a5-768b75bea1f0',
                        creator: 'MYSLLO',
                        gmtModified: '2023-03-27T10:41:32.276+0000',
                        fundInfoId: 'aa24e7d6-e9d2-4812-a4de-db9f7fab7c68',
                        transId: '4ee17e69-588a-4e29-bc24-18dd9f651586',
                        applicationNo: 'JZSC031501',
                        modifier: '0',
                        fundMeasure: 'P',
                        fundCurrency: 'MYR',
                        gmtCreate: '2023-03-27T10:41:32.276+0000',
                        deleted: 0,
                        fundCode: 'APDA',
                        sortOrder: 2,
                        fundAllocation: '30',
                        allocationAccount: null,
                        id: 'a79c30c8-c0b8-442f-a283-ebd90fd9f03f',
                        fundName: null,
                      },
                      {
                        coverageId: '2fdd0f0e-f476-457c-a3a5-768b75bea1f0',
                        creator: 'MYSLLO',
                        gmtModified: '2023-03-27T10:41:32.279+0000',
                        fundInfoId: 'aa24e7d6-e9d2-4812-a4de-db9f7fab7c68',
                        transId: '4ee17e69-588a-4e29-bc24-18dd9f651586',
                        applicationNo: 'JZSC031501',
                        modifier: '0',
                        fundMeasure: 'P',
                        fundCurrency: 'MYR',
                        gmtCreate: '2023-03-27T10:41:32.279+0000',
                        deleted: 0,
                        fundCode: 'ACFA',
                        sortOrder: 3,
                        fundAllocation: '20',
                        allocationAccount: null,
                        id: '52c6214f-ebec-4896-a41d-df559ccf5a0d',
                        fundName: null,
                      },
                    ],
                    gmtCreate: '2023-03-27T10:41:32.266+0000',
                    deleted: 0,
                    portfolioId: null,
                    portfolioType: null,
                    id: 'aa24e7d6-e9d2-4812-a4de-db9f7fab7c68',
                  },
                ],
                productCategory: null,
                payPeriod: '5',
                fundChartDataUrl: null,
                payPeriodUnit: 'Y',
                originalCoi: null,
                discountType: null,
                coverageInsuredList: [
                  {
                    coverageId: '2fdd0f0e-f476-457c-a3a5-768b75bea1f0',
                    creator: 'MYSLLO',
                    gmtModified: '2023-03-27T10:41:32.258+0000',
                    clientId: '16e0223d-b731-427c-82d7-ab0de3feb221',
                    clientName: 'Gerry Emard',
                    transId: '4ee17e69-588a-4e29-bc24-18dd9f651586',
                    applicationNo: 'JZSC031501',
                    modifier: '0',
                    gmtCreate: '2023-03-27T10:41:32.258+0000',
                    deleted: 0,
                    policyId: 'AL010472',
                    insuredSeqNum: '1',
                    insuredIndex: '0',
                    id: '58cdeb67-698a-4215-a4d4-2c624206aa9d',
                  },
                ],
                semiAnnualPrem: 3680,
                productType: 'RT',
                quarterlyPrem: 1840,
                indemnifyAgePeriod: null,
                coverageNum: '24',
                coverageLoadingList: null,
                planMedexSmre: null,
                planBusinessCode: null,
                payAgePeriod: null,
                occupationRate: null,
                isExempt: null,
                fundVisible: null,
              },
              name: 'RT',
              items: [
                {
                  coverageId: 'd81fda54-96b3-40ba-86c0-616c4b8bb2ed',
                  basePremiumAF: 1840,
                  basePremiumBE: 0,
                  annualPremAF: null,
                  annualPremBE: null,
                  sumAssuredBE: null,
                  payPeriodBE: null,
                  sumAssuredAF: null,
                  payPeriodAF: null,
                },
              ],
            },
          ],
          id: '81eab4a0-c9af-4c0f-a68e-7b4eac6e74ad',
          customizeOptionName: null,
          optionName: 'RT',
        },
        {
          creator: null,
          gmtModified: null,
          sustainable: 'Y',
          applied: null,
          transId: null,
          applicationNo: 'JZSC031501',
          modifier: null,
          remark: '[]',
          gmtCreate: null,
          version: 129,
          deleted: 0,
          round: 2,
          policyId: 'AL010472',
          selectedOptions: [
            {
              rtCoverage: null,
              name: 'increasePrem',
              items: [
                {
                  coverageId: '2fdd0f0e-f476-457c-a3a5-768b75bea1f0',
                  basePremiumAF: null,
                  basePremiumBE: null,
                  annualPremAF: 15830,
                  annualPremBE: 10330,
                  sumAssuredBE: null,
                  payPeriodBE: null,
                  sumAssuredAF: null,
                  payPeriodAF: null,
                },
              ],
            },
            {
              rtCoverage: {
                discountRate: null,
                discount: 0,
                planName: null,
                planCategory: null,
                coverageNo: null,
                initialPrem: 550,
                productName: null,
                embedIndicator: null,
                occupationLoading: null,
                occupationType: null,
                coverageExclusionList: null,
                calculateBy: null,
                loadingPremium: 0,
                id: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                embedFlag: null,
                underwritingType: null,
                priority: null,
                coreCode: 'RT07',
                unionInsuredSeqNum: null,
                saWaiver: null,
                rspPremiumTerm: null,
                grossPremium: 550,
                premiumTermType: null,
                annualizedPrem: 2200,
                gmtModified: null,
                finalCoi: null,
                componentDescriptionLocal: null,
                premiumMode: null,
                loadedPremium: 550,
                timeRiskMark: null,
                laPremium: 550,
                rsp: null,
                indemnifyPeriodUnit: 'Y',
                sumAssured: null,
                jointLifeNo: '00',
                indemnifyPeriod: '5',
                riskType: null,
                laCategory: null,
                customerSegment: null,
                componentDescriptionEn: null,
                benefitSubType: null,
                creator: null,
                extraCoi: null,
                coverageBenefitsList: null,
                packageId: null,
                coverageRemarkList: null,
                gmtCreate: null,
                subProductType: null,
                deleted: 0,
                productCode: null,
                numberOfUnits: null,
                annualLimit: null,
                policyId: 'AL010472',
                basePremium: 550,
                stampDuty: null,
                loadingRule: null,
                rspCharge: null,
                packageCode: null,
                backDay: null,
                instalmentPremiumWithTax: 550,
                matureDate: null,
                annualPrem: 2200,
                currencyCode: 'MYR',
                upToAge: null,
                notManualRemove: null,
                transId: null,
                applicationNo: 'JZSC031501',
                modifier: null,
                pid: 'RTIL',
                systemAutoAddInd: null,
                pbCodes: null,
                productLine: null,
                isBack: null,
                compareSeq: null,
                isExemptions: null,
                monthlyPrem: 183.33,
                waiveProductList: null,
                lifeNo: '01',
                isMain: 'N',
                tax: null,
                hospitalPlanCode: null,
                payerIndicator: null,
                unit: null,
                loanInfoList: null,
                taxAmount: 0,
                coverageDecision: null,
                sustainabilityChecking: null,
                riderNo: null,
                sinceCertificateYear: 1,
                coverageFundInfoList: [
                  {
                    totalFundAllocation: '100',
                    coverageId: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                    autoRebalancingStatus: null,
                    creator: 'MYSLLO',
                    gmtModified: '2023-03-27T10:19:06.633+0000',
                    transId: 'df4b297e-0a04-4bef-969c-e593ec30f3b7',
                    applicationNo: 'JZSC031501',
                    modifier: '0',
                    autoRebalancingType: null,
                    ownFundInfoList: [
                      {
                        coverageId: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                        creator: 'MYSLLO',
                        gmtModified: '2023-03-27T10:19:06.639+0000',
                        fundInfoId: '06fff2e0-44a0-492d-ab9c-af655e68350f',
                        transId: 'df4b297e-0a04-4bef-969c-e593ec30f3b7',
                        applicationNo: 'JZSC031501',
                        modifier: '0',
                        fundMeasure: 'P',
                        fundCurrency: 'MYR',
                        gmtCreate: '2023-03-27T10:19:06.639+0000',
                        deleted: 0,
                        fundCode: 'APEA',
                        sortOrder: 1,
                        fundAllocation: '50',
                        allocationAccount: null,
                        id: 'd955e0e3-7f7c-4dc2-9db3-74ad8343d898',
                        fundName: null,
                      },
                      {
                        coverageId: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                        creator: 'MYSLLO',
                        gmtModified: '2023-03-27T10:19:06.642+0000',
                        fundInfoId: '06fff2e0-44a0-492d-ab9c-af655e68350f',
                        transId: 'df4b297e-0a04-4bef-969c-e593ec30f3b7',
                        applicationNo: 'JZSC031501',
                        modifier: '0',
                        fundMeasure: 'P',
                        fundCurrency: 'MYR',
                        gmtCreate: '2023-03-27T10:19:06.642+0000',
                        deleted: 0,
                        fundCode: 'APDA',
                        sortOrder: 2,
                        fundAllocation: '30',
                        allocationAccount: null,
                        id: '7faf61d2-52b3-490e-90cc-c228f2976eea',
                        fundName: null,
                      },
                      {
                        coverageId: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                        creator: 'MYSLLO',
                        gmtModified: '2023-03-27T10:19:06.645+0000',
                        fundInfoId: '06fff2e0-44a0-492d-ab9c-af655e68350f',
                        transId: 'df4b297e-0a04-4bef-969c-e593ec30f3b7',
                        applicationNo: 'JZSC031501',
                        modifier: '0',
                        fundMeasure: 'P',
                        fundCurrency: 'MYR',
                        gmtCreate: '2023-03-27T10:19:06.645+0000',
                        deleted: 0,
                        fundCode: 'ACFA',
                        sortOrder: 3,
                        fundAllocation: '20',
                        allocationAccount: null,
                        id: '4340fb1a-5312-44fc-b5ae-f85b361b56ce',
                        fundName: null,
                      },
                    ],
                    gmtCreate: '2023-03-27T10:19:06.633+0000',
                    deleted: 0,
                    portfolioId: null,
                    portfolioType: null,
                    id: '06fff2e0-44a0-492d-ab9c-af655e68350f',
                  },
                ],
                productCategory: null,
                payPeriod: '5',
                fundChartDataUrl: null,
                payPeriodUnit: 'Y',
                originalCoi: null,
                discountType: null,
                coverageInsuredList: [
                  {
                    coverageId: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                    creator: 'MYSLLO',
                    gmtModified: '2023-03-27T10:19:06.623+0000',
                    clientId: '16e0223d-b731-427c-82d7-ab0de3feb221',
                    clientName: 'Gerry Emard',
                    transId: 'df4b297e-0a04-4bef-969c-e593ec30f3b7',
                    applicationNo: 'JZSC031501',
                    modifier: '0',
                    gmtCreate: '2023-03-27T10:19:06.623+0000',
                    deleted: 0,
                    policyId: 'AL010472',
                    insuredSeqNum: '1',
                    insuredIndex: '0',
                    id: '58fe7244-3350-4f0c-b3b0-42a18698752f',
                  },
                ],
                semiAnnualPrem: 1100,
                productType: 'RT',
                quarterlyPrem: 550,
                indemnifyAgePeriod: null,
                coverageNum: '24',
                coverageLoadingList: null,
                planMedexSmre: null,
                planBusinessCode: null,
                payAgePeriod: null,
                occupationRate: null,
                isExempt: null,
                fundVisible: null,
              },
              name: 'RT',
              items: [
                {
                  coverageId: '63e86aa6-23c1-494b-8d23-a1c36ed32230',
                  basePremiumAF: 550,
                  basePremiumBE: 0,
                  annualPremAF: null,
                  annualPremBE: null,
                  sumAssuredBE: null,
                  payPeriodBE: null,
                  sumAssuredAF: null,
                  payPeriodAF: null,
                },
              ],
            },
          ],
          id: 'c000d566-45d6-438e-b382-d3d26a9c2ed1',
          customizeOptionName: null,
          optionName: 'increasePrem&RT',
        },
      ],
    };

    const result = judgeDisplaySustainabiliy({
      businessData,
    });

    expect(result).toBeTruthy();
  });
  test('no sustainable is Y', () => {
    const businessData = {
      sustainabilityOptions: [
        {
          id: '48b46e78-2e64-4004-89db-07d6b53eabf7',
          creator: 'IDNMAR@id.fwd.com',
          gmtCreate: '2023-03-31T09:55:25.000+0000',
          modifier: '0',
          gmtModified: '2023-03-31T09:55:25.000+0000',
          deleted: 0,
          transId: '1ee3cab0-a43c-48ce-9f70-d4e2f30f68a1',
          version: 3,
          round: 0,
          optionName: null,
          applicationNo: '0164601377',
          policyId: '64601377',
          sustainable: 'I',
          applied: null,
          remark:
            '[{"code":"CUST_ERROR","id":"premium","label":{"en":"Total AV (High) until the end of the coverage period is negative. Please add premium","id":"Total Nilai Investasi tidak cukup untuk memberikan perlindungan hingga akhir masa asuransi. Silakan tambahkan premium"},"pid":"FIL","type":"error"}]',
          customizeOptionName: null,
          selectedOptions: null,
        },
      ],
    };
    const result = judgeDisplaySustainabiliy({ businessData });

    expect(result).not.toBeTruthy();
  });
});
