const CLAIMPAYABLEITEM = {
  assessorOverrideAmount: null,
  assessorOverridePercentage: null,
  assessorOverrideMultiple: null,
  benefitCategory: '',
  benefitTypeCode: '',
  causeOfIncident: '',
  claimDecision: 'A',
  claimNo: '',
  creator: '',
  declineCode: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentDate: null,
  incidentId: '',
  insuredId: '',
  lifePayable: null,
  modifier: '',
  payableAmount: 0,
  policyNo: '',
  policyYear: null,
  primaryDiagnosisCode: '',
  productCode: '',
  remark: '',
  systemCalculationAmount: 0,
  transId: '',
  treatmentPayableList: [],
  paymentAcceptedResult: '',
  assessmentResult: '',
  paymentAssessmentResult: '',
  mainProductCode: '',
  memberNo: '',
  hasCallExternalSystem: null,
};

// 治疗层级的赔付金
const TREATMENTPAYABLEITEM = {
  assessorOverrideAmount: null,
  assessorOverrideDays: null,
  assessorOverrideDeductible: null,
  assessorOverridePercentage: null,
  assessorOverrideMultiple: null,
  benefitAmount: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  claimNo: '',
  creator: '',
  dateOfAdmission: null,
  dateOfConsultation: null,
  dateOfDischarge: null,
  deductibleAmount: null,
  deductibleDays: null,
  deleted: 0,
  expenseAmount: null,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  invoicePayableList: [],
  modifier: '',
  payableAmount: null,
  payableDays: null,
  payableId: '',
  policyNo: '',
  process: [],
  productCode: '',
  reimbursementPercentage: null,
  reimbursementMultiple: null,
  remark: '',
  systemCalculationAmount: 0,
  transId: '',
  treatmentId: '',
};

const ACCIDENT_BENEFIT_PAYABLE_ITEM = {
  maxAmountPerWeek: null,
  amountPerWeek: null,
  assessorOverrideAmount: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  claimDecision: '',
  claimNo: '',
  creator: '',
  declineCode: '',
  deleted: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  modifier: '',
  payableAmount: null,
  payableDays: null,
  payableId: '',
  policyNo: '',
  productCode: '',
  remainingDays: null,
  remark: '',
  saPercentage: null,
  saPercentagePerWeek: null,
  systemCalculationAmount: null,
  transId: '',
  treatmentId: '',
  treatmentPayableId: '',
  payableYears: 1,
  saPercentagePerYear: null,
  remainingYears: null,
  saPercentagePerDisability: null,
  accumulatedAmount: null,
};

// 账单层级的赔付金
const INVOICEPAYABLEITEM = {
  assessorOverrideAmount: null,
  benefitTypeCode: '',
  claimNo: '',
  creator: '',
  deleted: 0,
  expenseAmount: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  invoiceId: '',
  modifier: '',
  payableAmount: null,
  payableId: '',
  policyNo: '',
  productCode: '',
  serviceItemPayableList: [],
  systemCalculationAmount: 0,
  transId: '',
  treatmentId: '',
  treatmentPayableId: '',
  benefitItemPayableList: [],
};
// 费用项层级的赔付金
const SERVICEPAYABLEITEM = {
  assessorOverrideAmount: null,
  benefitItemCode: '',
  benefitTypeCode: '',
  calculationAmount: 0,
  calculationDays: 0,
  calculationPerDay: 0,
  claimNo: '',
  coInsuranceAmount: 0,
  creator: '',
  deductibleAmount: 0,
  deleted: 0,
  expenseAmount: 0,
  gmtCreate: null,
  gmtModified: null,
  id: '',
  incidentId: '',
  invoiceId: '',
  invoicePayableId: '',
  modifier: '',
  payableAmount: 0,
  payableDays: 0,
  payableId: '',
  payablePerDay: 0,
  policyNo: '',
  process: [],
  productCode: '',
  remark: '',
  serviceItem: '',
  serviceItemId: '',
  systemCalculationAmount: 0,
  transId: '',
  treatmentId: '',
  treatmentPayableId: '',
};

// 手术赔付金
const PROCEDUREITEMPAYABLE = {
  allowanceType: null,
  assessorOverrideAmount: null,
  assessorOverrideDays: null,
  assessorOverrideDeductible: null,
  assessorOverrideMultiple: null,
  benefitAmount: null,
  benefitItemCode: null,
  benefitTypeCode: null,
  claimAdjustment: null,
  claimDecision: null,
  claimNo: null,
  claimNumber: null,
  claimOccurrenceNo: null,
  creator: null,
  declineCode: null,
  deleted: null,
  expectOperation: null,
  expenseAmount: null,
  gmtCreate: null,
  gmtModified: null,
  id: null,
  incidentId: null,
  kjCode: null,
  minReferenceDate: null,
  modifier: null,
  operationDate: null,
  payableAmount: null,
  payableDays: null,
  payableId: null,
  policyCurrency: null,
  policyNo: null,
  procedureCode: null,
  procedureId: null,
  productCode: null,
  reimbursementMultiple: null,
  remark: null,
  systemCalculationAmount: null,
  systemPayableDays: null,
  transId: null,
  treatmentId: null,
  treatmentPayableId: null,
};

const OTHERPROCEDUREITEMPAYABLE = {
  allowanceType: null,
  assessorOverrideAmount: null,
  assessorOverrideDays: null,
  assessorOverrideDeductible: null,
  assessorOverrideMultiple: null,
  benefitAmount: null,
  benefitItemCode: null,
  benefitTypeCode: null,
  claimAdjustment: null,
  claimDecision: null,
  claimNo: null,
  claimNumber: null,
  claimOccurrenceNo: null,
  creator: null,
  declineCode: null,
  deleted: null,
  expectOperation: null,
  expenseAmount: null,
  gmtCreate: null,
  gmtModified: null,
  id: null,
  incidentId: null,
  minReferenceDate: null,
  modifier: null,
  otherProcedureId: null,
  payableAmount: null,
  payableDays: null,
  payableId: null,
  policyCurrency: null,
  policyNo: null,
  productCode: null,
  reimbursementMultiple: null,
  remark: null,
  systemCalculationAmount: null,
  systemPayableDays: null,
  transId: null,
  treatmentId: null,
  treatmentPayableId: null,
};
const LIFEPAYABLE = {
  claimNo: null,
  gmtModified: null,
  transId: null,
  modifier: null,
  registered: null,
  policyNo: null,
  remark: null,
  minReferenceDate: null,
  calculationAmount: null,
  payableAmount: null,
  treatmentId: null,
  payableId: null,
  payableDays: null,
  benefitTypeCode: null,
  determinationDate: null,
  reimbursementMultiple: null,
  id: null,
  claimNumber: null,
  policyCurrency: null,
  amountType: null,
  creator: null,
  claimDecision: null,
  appealRequestDecision: null,
  systemCalculationAmount: 0,
  reimbursementPercentage: 100,
  assessorOverrideAmount: null,
  manualAdd: null,
  gmtCreate: null,
  benefitItemCode: null,
  deleted: null,
  productCode: null,
  assessorOverrideMultiple: null,
  expectOperation: null,
  claimOccurrenceNo: null,
  incidentId: null,
  paymentDate: null,
  claimAdjustment: null,
  benefitPayableLimitInfoList: null,
};

export {
  CLAIMPAYABLEITEM,
  TREATMENTPAYABLEITEM,
  ACCIDENT_BENEFIT_PAYABLE_ITEM,
  INVOICEPAYABLEITEM,
  SERVICEPAYABLEITEM,
  PROCEDUREITEMPAYABLE,
  OTHERPROCEDUREITEMPAYABLE,
  LIFEPAYABLE,
};
