enum ExpandEvent {
  COLLAPSE_ALL = 'COLLAPSE_ALL',
  EXPAND_ALL = 'EXPAND_ALL',
  EXPAND_TARGET_SECTIONS = 'EXPAND_TARGET_SECTIONS',
  EXPAND_SINGLE_SECTION = 'EXPAND_SINGLE_SECTION',
}

export default ExpandEvent;
