import type { ApiResponse } from '@/dtos/ApiResponse';

type PolicyInfoListProductInfoList = {
  id: string;
  creator: any;
  gmtCreate: any;
  modifier: any;
  gmtModified: any;
  deleted: any;
  transId: any;
  policyId: string;
  lifeNumber: string;
  coverageSeq: string;
  riderSeq: string;
  productCode: string;
  benefitPlan: string;
  insuredId: string;
  issueEffectiveDate: string;
  riskCessationDate: string;
  sumAssured: number;
  currency: string;
  riskStatus: string;
  beyondNel: any;
  insuredName: string;
  coverageType: any;
  premiumAmount: number;
  premiumStatus: string;
  aliasProductCode: any;
  aliasProductName: any;
  payToDate: string;
  benefitTypeInfoList: any;
  shareLimitInfoList: any;
  loadingList: any;
  productType: any;
  coverageKey: string;
  productName: string;
  policyYear: any;
  savingAccount: any;
  cancerUnsecuredSign: any;
  revampDate: string;
  revampTabName: any;
};

type PolicyInfoList = {
  policyId: string;
  internalPolicyId: string;
  policySource: string;
  mainProductCode: string;
  mainProductName: string;
  riskStatus: string;
  issueEffectiveDate: string;
  riskCessationDate: any;
  riskCommenceDate: string;
  paymentMode: string;
  paymentMethod: any;
  payToDate: string;
  premiumPaymentMethod: string;
  nextClaimPremium: any;
  premiumStatus: string;
  transactionStatus: any;
  sourceSystem: string;
  premiumAmount: number;
  paidPremium: any;
  lastPaymentDate: any;
  billingCurrency: any;
  pdType: any;
  insured: {
    firstName: string;
    middleName: string;
    surname: string;
    gender: string;
    dateOfBirth: string;
    occupationCode: string;
    phoneNo: string;
    clientId: string;
    address: string;
    smoker: any;
    email: string;
    vip: any;
    postCode: string;
    memberNo: any;
    dependentNo: any;
    primaryInsuredName: any;
  };
  policyOwner: {
    firstName: string;
    middleName: string;
    surname: string;
    gender: string;
    dateOfBirth: string;
    occupationCode: string;
    phoneNo: string;
    clientId: string;
    address: string;
    smoker: any;
    email: string;
    vip: any;
    postCode: string;
    memberNo: any;
    dependentNo: any;
    primaryInsuredName: any;
    relationshipWithInsured: any;
  };
  agent: {
    firstName: string;
    middleName: any;
    surname: string;
    gender: any;
    dateOfBirth: any;
    occupationCode: any;
    phoneNo: any;
    clientId: any;
    address: any;
    smoker: any;
    email: string;
    vip: any;
    postCode: any;
    memberNo: any;
    dependentNo: any;
    primaryInsuredName: any;
  };
  payor: {
    firstName: string;
    middleName: string;
    surname: string;
    gender: string;
    dateOfBirth: string;
    occupationCode: string;
    phoneNo: string;
    clientId: string;
    address: string;
    smoker: any;
    email: string;
    vip: any;
    postCode: string;
    memberNo: any;
    dependentNo: any;
    primaryInsuredName: any;
  };
  beneficiaryOwner: any;
  productInfoList: PolicyInfoListProductInfoList[];
  policyExclusionList: any[];
  beneficiaryList: any;
  policyNoteList: any;
  loanList: any;
  transactionLogPolicyNotesUrl: string;
  policyCategory: any;
  validFlag: any;
  familyPolicyFlag: boolean;
  companyCode: any;
  contractType: string;
  subCompanyCode: any;
  onlyPolicyNote: boolean;
};

type PosHistoryList = {
  policyId: string;
  mainProductCode: string;
  transactionDate: string;
  transactionCode: string;
  transactionStatus: string;
  effectiveDate: string;
  completeDate: any;
  applyToProductCodeList: string[];
  transferType: any;
  transactionName: any;
  transactionNumber: string;
  sourceSystem: string;
  reverseFlag: string;
  userId: string;
  businessNo: any;
  caseStatus: any;
  decision: any;
  submissionChannel: any;
  submissionDate: string;
  currentActivity: any;
  assignee: any;
  businessProcessId: any;
  inquiryBusinessNo: any;
  caseCategory: any;
  applyToProductNameList: string[];
  mainProductName: string;
};

type CoverageList = {
  id: string;
  coverageType: string;
  coverageStatus: string;
  monthPeriod: string;
  currency: any;
  tsar: number;
  tsarCalculationCategory: string;
  roleInd: string;
  distributionChannel: any;
  gsIndicator: any;
  benefitSubType: any;
  premiumType: any;
  additionalFunctionType: any;
  submissionChannel: any;
  currentAgentChannelCode: any;
  componentCode: any;
  displayStyle: string;
};

type SummaryCoverageMaxPerLifeData = {
  tsar: number;
  componentCode: string;
  tsarCalculationCategory: string;
  policyStatus: string;
  riskType: string;
  monthPeriod: string;
  roleInd: string;
};

type SummaryCoverageOpusSummary = {
  roleInd: string;
  benefitType: string;
  componentCode: string;
  newTotalTsar: number;
  pendingTotalTsar: number;
  existingTotalTsar: number;
  total: number;
  order: number;
};

type SummaryCoverage = {
  tsarCategoryData: any[];
  maxPerLifeData: SummaryCoverageMaxPerLifeData[];
  summary: {
    roleInd: string;
    benefitType: any;
    componentCode: any;
    newTotalTsar: number;
    pendingTotalTsar: number;
    existingTotalTsar: number;
    total: number;
    order: number;
  }[];
  opusSummary: SummaryCoverageOpusSummary[];
};

type ResultData = {
  sideBarOverallList: {
    regionCode: string;
    keyClientId: string;
    businessCode: string;
    clientIdList: string[];
    ownerPolicyIdList: string[];
    insuredPolicyIdList: string[];
    familyMainInsuredPolicyIdList: any;
    beneficiaryPolicyIdList: any;
    payorPolicyIdList: any;
    beneficiaryOwnerPolicyIdList: any;
    clientInfo: {
      firstName: string;
      middleName: string;
      surname: string;
      gender: string;
      dateOfBirth: string;
      occupationCode: string;
      phoneNo: string;
      clientId: string;
      address: string;
      smoker: any;
      email: string;
      vip: any;
      postCode: string;
      memberNo: any;
      dependentNo: any;
      primaryInsuredName: any;
    };
    policyInfoList: PolicyInfoList[];
  }[];
  posHistoryList: PosHistoryList[];
  claimHistoryList: any[];
  coverageList: CoverageList[];
  summaryCoverage: SummaryCoverage;
  businessNo: string;
  clientId: string;
  regionCode: string;
  key: any;
  encrypted: boolean;
};

export interface InsuredPolicyResponseData extends ApiResponse {
  resultData: ResultData;
}
