export default {
  isShow: {
    isShowAI: true,
    isShowChat: false,
    isShowRemark: false,
    isShowPending: false,
    isShow360: false,
  },
  isSwitchOn: false,
  isExpanded: false,
  widthSider: {
    widthTab: 44,
    widthSwitchOn: 382,
    widthExpanded: 836,
  },
  listDisplayConfig: [],
  processInfo: {
    caseCategory: '',
    activityKey: '',
  },
  processShow: {
    isShowAI: true,
    isShowChat: true,
    isShowRemark: false,
    isShowPending: false,
    isShow360: false,
    isShowTools: false,
    isShowIntegration: false,
  },
  tabAuthorized: [],
  c360Tab: 'policy',

  triggerTimeout: false,
  triggerDependencies: {},
  autoTrigger: false,
  autoTriggerConfig: [],
  triggerModalData: {},
  activeTask: {},
  taskDetail: null,
  triggerActiveTab: null,
};
