import { renderHook } from '@testing-library/react-hooks';
import useGetRelatedRider from 'process/NB/ManualUnderwriting/_hooks/useGetRelatedRider';

jest.mock('process/NB/ManualUnderwriting/_hooks/useGetCoverageProductList', () => {
  return jest
    .fn(() => {
      return [];
    })
    .mockImplementationOnce(() => {
      return ['ED05', 'AC03', 'CI04'];
    });
});

jest.mock('dva', () => {
  const actual = jest.requireActual('dva');
  return {
    ...actual,
    useSelector: jest.fn(() => {
      return {
        basicPlanProductFeatureList: [
          {
            regionCode: 'VN',
            productCode: 'ED05',
            productName: 'FWD Con vươn xa 2.0',
            mortalityClass: 'C',
            basicRiderCode: 'B',
            wpPbCode: null,
            saEditInd: null,
            saFollowCode: null,
            policyTermEditInd: null,
            policyTermFollowCode: null,
            premiumTermEditInd: null,
            premiumTermFollowCode: null,
            exclusionEditInd: null,
            underwritingDecisionEditInd: null,
            underwritingApproach: null,
            premiumType: 'RP',
            channel: 'AGENCY',
            isSupported: 'Y',
            defaultNfoCode: 'RPU',
            loanProtection: null,
            benefitPlanInd: 'Y',
            productLegacy: null,
            livingBenefitCode: null,
            packageCode: null,
            waiveCode: null,
            ageFormularCode: 'ALB',
            applicableToRole: null,
            bankPayoutInd: null,
            benefitPlanEditInd: null,
            ropInd: null,
            saMultiplierInd: null,
            jointLifeAllowInd: null,
            riderRequiredInd: 'N',
            lifeCode: 'PI',
            maxNo: '1',
            linkProductCode: null,
            subProductType: 'ED',
            meTermFollowCode: null,
            feTermFollowCode: null,
            rateTermFollowCode: null,
            rider: false,
            relatedRider: [
              {
                regionCode: 'VN',
                productCode: 'ED05',
                productName: 'FWD Con vươn xa 2.0',
                mortalityClass: 'C',
                basicRiderCode: 'B',
                wpPbCode: null,
                saEditInd: null,
                saFollowCode: null,
                policyTermEditInd: null,
                policyTermFollowCode: null,
                premiumTermEditInd: null,
                premiumTermFollowCode: null,
                exclusionEditInd: null,
                underwritingDecisionEditInd: null,
                underwritingApproach: null,
                premiumType: 'RP',
                channel: 'AGENCY',
                isSupported: 'Y',
                defaultNfoCode: 'RPU',
                loanProtection: null,
                benefitPlanInd: 'Y',
                productLegacy: null,
                livingBenefitCode: null,
                packageCode: null,
                waiveCode: null,
                ageFormularCode: 'ALB',
                applicableToRole: null,
                bankPayoutInd: null,
                benefitPlanEditInd: null,
                ropInd: null,
                saMultiplierInd: null,
                jointLifeAllowInd: null,
                riderRequiredInd: 'N',
                lifeCode: 'PI',
                maxNo: '1',
                linkProductCode: null,
                subProductType: 'ED',
                meTermFollowCode: null,
                feTermFollowCode: null,
                rateTermFollowCode: null,
                rider: false,
              },
            ],
          },
        ],
        otherPlanProductFeatureList: [
          {
            regionCode: 'VN',
            productCode: 'AC03',
            productName: 'FWD CARE Bảo hiểm tai nạn',
            mortalityClass: 'C',
            basicRiderCode: 'R',
            wpPbCode: null,
            saEditInd: null,
            saFollowCode: null,
            policyTermEditInd: null,
            policyTermFollowCode: null,
            premiumTermEditInd: null,
            premiumTermFollowCode: null,
            exclusionEditInd: null,
            underwritingDecisionEditInd: null,
            underwritingApproach: null,
            premiumType: 'RP',
            channel: 'AGENCY',
            isSupported: 'Y',
            defaultNfoCode: null,
            loanProtection: null,
            benefitPlanInd: 'Y',
            productLegacy: '',
            livingBenefitCode: null,
            packageCode: null,
            waiveCode: null,
            ageFormularCode: 'ALB',
            applicableToRole: null,
            bankPayoutInd: null,
            benefitPlanEditInd: null,
            ropInd: null,
            saMultiplierInd: null,
            jointLifeAllowInd: null,
            riderRequiredInd: 'N',
            lifeCode: 'SI',
            maxNo: '99',
            linkProductCode: null,
            subProductType: null,
            meTermFollowCode: null,
            feTermFollowCode: null,
            rateTermFollowCode: null,
            rider: false,
            relatedRider: [
              {
                regionCode: 'VN',
                productCode: 'ED05',
                productName: 'FWD Con vươn xa 2.0',
                mortalityClass: 'C',
                basicRiderCode: 'B',
                wpPbCode: null,
                saEditInd: null,
                saFollowCode: null,
                policyTermEditInd: null,
                policyTermFollowCode: null,
                premiumTermEditInd: null,
                premiumTermFollowCode: null,
                exclusionEditInd: null,
                underwritingDecisionEditInd: null,
                underwritingApproach: null,
                premiumType: 'RP',
                channel: 'AGENCY',
                isSupported: 'Y',
                defaultNfoCode: 'RPU',
                loanProtection: null,
                benefitPlanInd: 'Y',
                productLegacy: null,
                livingBenefitCode: null,
                packageCode: null,
                waiveCode: null,
                ageFormularCode: 'ALB',
                applicableToRole: null,
                bankPayoutInd: null,
                benefitPlanEditInd: null,
                ropInd: null,
                saMultiplierInd: null,
                jointLifeAllowInd: null,
                riderRequiredInd: 'N',
                lifeCode: 'PI',
                maxNo: '1',
                linkProductCode: null,
                subProductType: 'ED',
                meTermFollowCode: null,
                feTermFollowCode: null,
                rateTermFollowCode: null,
                rider: false,
              },
            ],
          },
          {
            regionCode: 'VN',
            productCode: 'CI04',
            productName: 'FWD CARE Bảo hiểm bệnh hiểm nghèo 2.0',
            mortalityClass: 'C',
            basicRiderCode: 'R',
            wpPbCode: null,
            saEditInd: null,
            saFollowCode: null,
            policyTermEditInd: null,
            policyTermFollowCode: null,
            premiumTermEditInd: null,
            premiumTermFollowCode: null,
            exclusionEditInd: null,
            underwritingDecisionEditInd: null,
            underwritingApproach: null,
            premiumType: 'RP',
            channel: 'AGENCY',
            isSupported: 'Y',
            defaultNfoCode: null,
            loanProtection: null,
            benefitPlanInd: 'Y',
            productLegacy: '',
            livingBenefitCode: null,
            packageCode: null,
            waiveCode: null,
            ageFormularCode: 'ALB',
            applicableToRole: null,
            bankPayoutInd: null,
            benefitPlanEditInd: null,
            ropInd: null,
            saMultiplierInd: null,
            jointLifeAllowInd: null,
            requiredRiderCodeList: [],
            riderRequiredInd: 'N',
            lifeCode: 'SI',
            maxNo: '99',
            linkProductCode: null,
            subProductType: null,
            meTermFollowCode: null,
            feTermFollowCode: null,
            rateTermFollowCode: null,
            riderCodeList: [],
            rider: false,
            relatedRider: [
              {
                regionCode: 'VN',
                productCode: 'ED06',
                productName: 'FWD Con vươn xa 2.0',
                mortalityClass: 'C',
                basicRiderCode: 'B',
                wpPbCode: null,
                saEditInd: null,
                saFollowCode: null,
                policyTermEditInd: null,
                policyTermFollowCode: null,
                premiumTermEditInd: null,
                premiumTermFollowCode: null,
                exclusionEditInd: null,
                underwritingDecisionEditInd: null,
                underwritingApproach: null,
                premiumType: 'RP',
                channel: 'AGENCY',
                isSupported: 'Y',
                defaultNfoCode: 'RPU',
                loanProtection: null,
                benefitPlanInd: 'Y',
                productLegacy: null,
                livingBenefitCode: null,
                packageCode: null,
                waiveCode: null,
                ageFormularCode: 'ALB',
                applicableToRole: null,
                bankPayoutInd: null,
                benefitPlanEditInd: null,
                ropInd: null,
                saMultiplierInd: null,
                jointLifeAllowInd: null,
                riderRequiredInd: 'N',
                lifeCode: 'PI',
                maxNo: '1',
                linkProductCode: null,
                subProductType: 'ED',
                meTermFollowCode: null,
                feTermFollowCode: null,
                rateTermFollowCode: null,
                rider: false,
              },
            ],
          },
        ],
      };
    }),
  };
});

describe('useGetRelatedRider', () => {
  test('attach basic product & coverage rider duplicate test', () => {
    const renderer = renderHook(() => useGetRelatedRider());

    expect(renderer.result.current).toEqual([
      {
        regionCode: 'VN',
        productCode: 'ED05',
        productName: 'FWD Con vươn xa 2.0',
        mortalityClass: 'C',
        basicRiderCode: 'B',
        wpPbCode: null,
        saEditInd: null,
        saFollowCode: null,
        policyTermEditInd: null,
        policyTermFollowCode: null,
        premiumTermEditInd: null,
        premiumTermFollowCode: null,
        exclusionEditInd: null,
        underwritingDecisionEditInd: null,
        underwritingApproach: null,
        premiumType: 'RP',
        channel: 'AGENCY',
        isSupported: 'Y',
        defaultNfoCode: 'RPU',
        loanProtection: null,
        benefitPlanInd: 'Y',
        productLegacy: null,
        livingBenefitCode: null,
        packageCode: null,
        waiveCode: null,
        ageFormularCode: 'ALB',
        applicableToRole: null,
        bankPayoutInd: null,
        benefitPlanEditInd: null,
        ropInd: null,
        saMultiplierInd: null,
        jointLifeAllowInd: null,
        riderRequiredInd: 'N',
        lifeCode: 'PI',
        maxNo: '1',
        linkProductCode: null,
        subProductType: 'ED',
        meTermFollowCode: null,
        feTermFollowCode: null,
        rateTermFollowCode: null,
        rider: false,
      },
      {
        regionCode: 'VN',
        productCode: 'ED06',
        productName: 'FWD Con vươn xa 2.0',
        mortalityClass: 'C',
        basicRiderCode: 'B',
        wpPbCode: null,
        saEditInd: null,
        saFollowCode: null,
        policyTermEditInd: null,
        policyTermFollowCode: null,
        premiumTermEditInd: null,
        premiumTermFollowCode: null,
        exclusionEditInd: null,
        underwritingDecisionEditInd: null,
        underwritingApproach: null,
        premiumType: 'RP',
        channel: 'AGENCY',
        isSupported: 'Y',
        defaultNfoCode: 'RPU',
        loanProtection: null,
        benefitPlanInd: 'Y',
        productLegacy: null,
        livingBenefitCode: null,
        packageCode: null,
        waiveCode: null,
        ageFormularCode: 'ALB',
        applicableToRole: null,
        bankPayoutInd: null,
        benefitPlanEditInd: null,
        ropInd: null,
        saMultiplierInd: null,
        jointLifeAllowInd: null,
        riderRequiredInd: 'N',
        lifeCode: 'PI',
        maxNo: '1',
        linkProductCode: null,
        subProductType: 'ED',
        meTermFollowCode: null,
        feTermFollowCode: null,
        rateTermFollowCode: null,
        rider: false,
      },
    ]);
  });
});
