import React from 'react';
import { FormItemInput, FormItemSelect } from 'basic/components/Form/FormSection';

export default (props: any) => {
  const { form, taskNotEditable, Account, FinInstCategory, BranchCategory } = props;
  return [
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      formName="accountOwnerName"
      maxLength={30}
      required
      labelId="venus_claim.label.accountOwnerName"
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      formName="accountOwnerSpellName"
      maxLength={90}
      required
      labelId="venus_claim.label.accountOwnerSpellName"
    />,
    <FormItemSelect
      form={form}
      disabled={taskNotEditable}
      required
      formName="accountCategory"
      labelId="venus_claim.label.accountCategory"
      dicts={Account}
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      required
      formName="accountNo"
      maxLength={40}
      labelId="venus_claim.label.accountNo"
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      formName="financialInstitutionCode"
      maxLength={10}
      required
      labelId="venus_claim.label.financialInstitutionCode"
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      formName="financialInstitutionName"
      required
      maxLength={60}
      labelId="venus_claim.label.financialInstitutionName"
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      required
      formName="financialInstitutionSpellName"
      maxLength={180}
      labelId="venus_claim.label.financialInstitutionSpellName"
    />,
    <FormItemSelect
      form={form}
      disabled={taskNotEditable}
      required
      formName="financialInstitutionCategory"
      labelId="venus_claim.label.financialInstitutionCategory"
      dicts={FinInstCategory}
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      formName="branchCode"
      maxLength={10}
      required
      labelId="venus_claim.label.branchCode"
    />,
    <FormItemInput
      form={form}
      disabled={taskNotEditable}
      formName="branchName"
      required
      maxLength={40}
      labelId="venus_claim.label.branchName"
    />,
    <FormItemSelect
      form={form}
      disabled={taskNotEditable}
      required
      formName="branchCategory"
      labelId="venus_claim.label.branchCategory"
      dicts={BranchCategory}
    />,
  ];
};
