import moment from 'moment';
import { tenant, Region } from '@/components/Tenant';

export default {
  informationData: {},
  currentActivity: {},
  processInstanceId: '',
  allCategoryList: [],
  classification: {},
  // 默认全选中
  tabs: ['case', 'insured', 'policy'],
  historyList: [],
  // 历史加载过的数据
  cacheHistoryData: {},
  pagination: {
    currentPage: 1,
    pageSize: 10,
    hasMore: true,
  },
  auditLogPagination: {
    currentPage: 1,
    pageSize: 20,
    sortName: 'date',
    sortOrder: 'desc',
    hasMore: true,
  },
  triggerPointCode: [],
  auditLogMounted: false,
  collapseActiveKey: ['AddInformationList'],
  newRecordCollapseActiveKey: [],
  addInformation: [
    {
      effectiveDate: moment().valueOf(),
      expiryDate: moment('2999-12-31').valueOf(),
      content: '',
      informationTab: tenant.region({
        [Region.MY]: ['case', 'insured', 'policy'],
        notMatch: ['case'],
      }),
      reason: null,
    },
  ],
  addInformations: [],
  taskId: '',
  lockInformationData: false,
  informationDataContactContent: [],
  listenList: [],
  callBackList: [],
  listenTaskIdList: [],
  changedFieldsOutsideCache: {
    categoryCode: '',
  },
  allCategoryHistory: [],
  showAddButton: false,
  isShowAllCategory: false,
  categroyReason: {
    field: '',
    value: [],
  },
  isShowInformationList: false,
  isShowAddBtn: true,
  saveHistoryActiveKey: false,
  taskStatus: '',
  latestaskId: '',
  currrentActivityCategory: {},
  cacheChatLink: {},
  categoryList: [],
  contentIndex: 1,
  isShowAddInformation: true,
  isDisabledAddButton: false,
  allCategoryTypeCode: {},
  defaultKey: '',
  isSelectedCategory: false,
  selectedTabs: [],
  caseCategory: '',
  forms: {},
  auditList: [],
  activityHistoryPanel: [],
  activityHistoryItem: '',
  expenderModel: 'history',
  addInformationBuffer: {},
  activeEditTabs: '',
  categoryReasonTemplate: [],
  appealCaseNoCover: false,
  ownCategoryReason: {},
};
