export default {
  reportListMap: {},
  activeTabKey: '',
  reportMetadata: {},
  searchDefault: {},
  tableReport: {},
  collapseState: false,
  covariance: {},
  statisticCode: '',
  batchSumUpStatistic: {},
  form: null,
  statisticCodeList: [],
  isPrintTable: true,
  printParams: {},
  clickdTab: false,
  previewModal: false,
  findStorage: {},
};
