export default {
  disabled: false,
  required: false,
  rules: [],
  mode: 'default',
  optionShowType: 'dictName',
  dictCode: 'dictCode',
  dictName: 'dictName',
  dictTypeCode: '',
  editable: undefined,
  labelId: undefined,
  allowClear: true,
  useError: true,
  multipleString: false,
  existCodes: [],
  onSelect: () => {},
  warningMessage: [],
  labelTypeCode: 'Label_BIZ_Claim',
  filterList: [],
  getPopupContainer: (triggerNode: any) => triggerNode.parentNode,
};
