const DropDownMap = {
  Common: ['documentType_i18n', 'Gender'],
  // eslint-disable-next-line max-len
  DiagnosisReport: [
    'RadioType',
    'AdvancedTreatment',
    'SequelaeOfStroke',
    'SupportNeedLv',
    'SurgeryType',
    'ProcedureDetail',
    'HistoExam',
    'OtherExam',
    'MNType',
    'HospitalStatus',
    'DisabilityLv',
    'CervicalCancerCin',
    'LaborConstrainedOfAmi',
    'NotifInsured',
    'DoctorSign',
    'DepthColorectalCancer',
    'PastDoctor',
    'MedicalHistory',
    'LNCommentFlag',
    'NursingFlag',
    'StrokeFlag',
    'CancerFlagI',
    'CancerFlagII',
    'CancerFlagIII',
    'CancerFlagIV',
    'CancerFlagV',
    'DisabilityFlag',
    'AMIFlag',
    'RadioThermoFlag',
    'AdvTreatmentFlag',
    'ThirdAdmissionYN',
    'Mastectomy',
    'SideforMastectomy',
    'BreastReconstruction',
    'SideforBreastReconstruction',
    'Ovariectomy',
    'SideforOvariectomy',
    'Hysterectomy',
    'CapabilitytoClaim_006_jp',
    'NeoplasmStage',
    'HistoDiagnosis_jp',
    'IntraepithelialCarcinoma',
    'HistoMethod_jp',
    'NotificationofDiagnosis',
    'HistoforIntraepithelial',
    'OncologyCode',
    'StageofIntraepithelial',
    'DistantMetastasis',
    'EligibleforLN',
    'AntiCancerMeds',
    'HormoneTreatment',
    'PainkillerforCancer',
    'PalliativeCare',
    'CalcuTypeforPalliative',
  ],
  HospitalizationReport: ['MedicalInst'],
  IncidentReport: ['ReporttoPolice', 'Drinking', 'MoveonSpot', 'DrivingLicense'],
  RequestForm: [
    'PaymentMethod',
    'applicationType',
    'BranchCategory',
    'Account',
    'ContactInfoType',
    'FinInstCategory',
    'BranchCategory',
    'RepCategory',
  ],
  DeathReport: [
    // eslint-disable-next-line max-len
    'ThirdAdmissionYN',
    'causeOfDeath',
    'DeathfromProcedure',
    'DeathType',
    'DeathRelatedPMH',
    'SurgeryType',
    'ProcedureDetail',
    'RemarkAvailable',
    'RadioThermoFlag',
    'RadioType',
    'PastDoctor',
    'DoctorSign',
  ],
  TreatmentReport: ['MedicalInst'],
  AnnuityForm: ['DistributionMethod', 'AnnuityPeriod', 'PreferredDistMethod'],
};
export default {
  ...DropDownMap,
  OtherDiagnosisReport: DropDownMap.DiagnosisReport,
};
