export default {
  taskDetail: {},
  businessData: {},
  processData: {
    clientInfoList: [],
    planInfoData: {},
    paymentList: [],
    chequeInfoList: [],
    charityOrganizationList: [],
    premiumPaymentCfgList: [],
    coverageList: [],
    policyDecision: [],
    policyExclusionList: [],
    policyAddressList: [],
    policyReplacement: {},
    takeOver: {},
    agentList: [],
  },
  entities: { clientMap: {} },
  initState: false,
  addressDict: {},
  errorLog: { errors: {}, errorCount: 0 },
  showModalType: '',

  // client
  expandedClientId: '',
  displayUWMELink: false,
  UWMeLinkAge: '',
  questionnaireSwitch: false,
  riskIndicatorConfigList: [],
  roleDicts: [],
  listDedupCheckCfg: [],
  authorisedSignatoryClientId: '',
  exchangeRate: {},
  currencyCode: '',
  regionalDefaultValue: {},
  nationalityList: [],
  idDisplayConfigList: [],
  linkDicts: {},
  tempAdd: {},
  editingClientId: '',

  numberofunitsList: [],
  planProductConfig: {
    requiredProductCodeList: [],
    basicPlanProductFeatureList: [],
    otherPlanProductFeatureList: [],
  },
  cfgRegionalDefaultValueList: [],
  addingLoadingItems: [],
  addingLoadingSelectedProduct: {},
  addDPRemarkSelectedProduct: {},
  addPopExclusionList: [],
  productSection: {},
  addDPRemarkItems: [],
  isShowPopUpDecision: false,
  coverageList: [],
  diffSource: {},
  addLoadingModalVisible: false,

  fecRiskMsg: '',
  defaultValueByCode: {}, //原本的字段 regionalDefaultValue
  paymentTransferModal: {
    show: false,
    data: {},
  },

  factoringHousesList: [],
  allFundConfigList: [],
  chequeEditStatus: '',
  clientNameList: [],

  contractTypeList: [],
  searchBankCodeList: [],
  bankCodeByRptAndCcList: [],
  premiumPaymentCfgList: [],
  planInfoAllAddressList: [],

  parentCodeAddress: {},
  cfgPlanProductOptions: {},
  clientNameDicts: [],
  modalData: {
    processData: {},
    distributionChannel: {
      // DistributionChannel模块
      bankStaffList: [],
      campaignList: [],
      bankChannelList: [],
      branchCodeList: [],
      agentChannelCode: null,
      distributionChannelList: {},
    },
    fund: {
      // Fund模块
      productCodeList: {},
      fundConfigList: {},
      fundInfo: {},
      fundList: [],
      fundTotal: {},
    },
    loanDetailList: [],
    policyReplacement: {
      // PolicyReplacement模块
      policyReplacementFlag: '',
      gsIndicator: '',
      replacementFirstInfo: {},
      replacementLastInfo: {},
      policyReplacementList: [],
    },
    takeOver: {
      // TakeOver模块
      takeOverInfo: {},
      takeOverList: [],
      productConfig: {},
    },
  },
  showTransferPayment: false,
  paymentAmountData: {},
  editingAssignee: '',
  occupationFullList: {},
  isShowRuleResultsModal: false,
  progressData: [],
  lastProgressData: [],
  progressDone: false,
  showEditModal: false,

  sustainabilityModal: {
    coverageList: [],
    sustainabilityOptions: [],
    possibleSusOptIdAndNameList: {},
    customizeSusOptIdList: [],
  },
  sustainabilityModalVisible: false,
  shouldCheckAMLOrCRRHighlight: false,

  premiumTransferModalData: {
    Show: false,
    resolve: null,
    reject: null,
    TaskDetail: {},
    errorMsgs: [],
  },

  warnNotices: [],
  auditLogExists: false,
  exclusionCopyRule: [],
  loadingCopyRule: [],
  warnNotices: [],
  auditLogExists: false,
  miscCommonHierarchy: [],
  isSaveDataComplete: true,
  distributionChannelDisplayMethod: null,
  needRefreshAgentInfo: null,
  facultativeInfo: null,
  loadFacutativeInfoChangeFlag: false, //for trigger get Facutative Info only when flag changes, no matter true or false
  retrieveExistCorpFromLA: 'N',
  displayUBOInfoFlag: 'N',
};
