enum SEARCHNAME {
  SERVICEITEM = 'SERVICEITEM',
  BANK = 'BANK',
  BANKBRANCH = 'BANKBRANCH',
  BANKBRANCHCOMPANY = 'BANKBRANCHCOMPANY',
  BANKBRANCHJP = 'BANKBRANCHJP',
  DIAGNOSIS = 'DIAGNOSIS',
  DICTIONARY = 'DICTIONARY',
  MEDICALPROVIDER = 'MEDICALPROVIDER',
  MEDICALPROVIDERTH = 'MEDICALPROVIDERTH',
  NATIONALITY = 'NATIONALITY',
  OCCUPATION = 'OCCUPATION',
  PARTOFBODYINJURED = 'PARTOFBODYINJURED',
  PRODUCT = 'PRODUCT',
  SURGERYPROCEDURE = 'SURGERYPROCEDURE',
  ADVANCEDMEDICALCN = 'ADVANCEDMEDICALCN',
}

export default SEARCHNAME;
